/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.analytics.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mavenagi.core.ObjectMappers;
import com.mavenagi.resources.conversation.types.ConversationFilter;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConversationAnalyticsRequest.Builder.class)
public final class ConversationAnalyticsRequest implements IConversationAnalyticsRequest {
    private final Optional<ConversationFilter> conversationFilter;

    private final Optional<String> timezone;

    private final Map<String, Object> additionalProperties;

    private ConversationAnalyticsRequest(
            Optional<ConversationFilter> conversationFilter,
            Optional<String> timezone,
            Map<String, Object> additionalProperties) {
        this.conversationFilter = conversationFilter;
        this.timezone = timezone;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Optional filter applied to refine the conversation data before processing.
     */
    @JsonProperty("conversationFilter")
    @java.lang.Override
    public Optional<ConversationFilter> getConversationFilter() {
        return conversationFilter;
    }

    /**
     * @return IANA timezone identifier (e.g., &quot;America/Los_Angeles&quot;).
     * When provided, time-based groupings (e.g., DAY) and date filters are evaluated in this timezone;
     * otherwise UTC is used.
     */
    @JsonProperty("timezone")
    @java.lang.Override
    public Optional<String> getTimezone() {
        return timezone;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConversationAnalyticsRequest && equalTo((ConversationAnalyticsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConversationAnalyticsRequest other) {
        return conversationFilter.equals(other.conversationFilter) && timezone.equals(other.timezone);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.conversationFilter, this.timezone);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<ConversationFilter> conversationFilter = Optional.empty();

        private Optional<String> timezone = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ConversationAnalyticsRequest other) {
            conversationFilter(other.getConversationFilter());
            timezone(other.getTimezone());
            return this;
        }

        /**
         * <p>Optional filter applied to refine the conversation data before processing.</p>
         */
        @JsonSetter(value = "conversationFilter", nulls = Nulls.SKIP)
        public Builder conversationFilter(Optional<ConversationFilter> conversationFilter) {
            this.conversationFilter = conversationFilter;
            return this;
        }

        public Builder conversationFilter(ConversationFilter conversationFilter) {
            this.conversationFilter = Optional.ofNullable(conversationFilter);
            return this;
        }

        /**
         * <p>IANA timezone identifier (e.g., &quot;America/Los_Angeles&quot;).
         * When provided, time-based groupings (e.g., DAY) and date filters are evaluated in this timezone;
         * otherwise UTC is used.</p>
         */
        @JsonSetter(value = "timezone", nulls = Nulls.SKIP)
        public Builder timezone(Optional<String> timezone) {
            this.timezone = timezone;
            return this;
        }

        public Builder timezone(String timezone) {
            this.timezone = Optional.ofNullable(timezone);
            return this;
        }

        public ConversationAnalyticsRequest build() {
            return new ConversationAnalyticsRequest(conversationFilter, timezone, additionalProperties);
        }
    }
}
