/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.analytics.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mavenagi.core.ObjectMappers;
import com.mavenagi.resources.conversation.types.ConversationField;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConversationRow.Builder.class)
public final class ConversationRow implements IRowBase {
    private final Map<String, CellData> data;

    private final Map<ConversationField, FieldValue> identifier;

    private final List<ConversationRowIdentifier> identifiers;

    private final Map<String, Object> additionalProperties;

    private ConversationRow(
            Map<String, CellData> data,
            Map<ConversationField, FieldValue> identifier,
            List<ConversationRowIdentifier> identifiers,
            Map<String, Object> additionalProperties) {
        this.data = data;
        this.identifier = identifier;
        this.identifiers = identifiers;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The actual row data, where keys represent column headers and values contain the respective metric results.
     * A column the metric could not measure is absent from the map, so a row can carry fewer
     * entries than there are headers.
     */
    @JsonProperty("data")
    @java.lang.Override
    public Map<String, CellData> getData() {
        return data;
    }

    /**
     * @return Keyed by field, so it cannot represent two groupings that share a key - notably two
     * intelligent fields. Use <code>identifiers</code>, which carries one entry per grouping in request
     * order.
     */
    @JsonProperty("identifier")
    public Map<ConversationField, FieldValue> getIdentifier() {
        return identifier;
    }

    /**
     * @return One entry per grouping, in the order the groupings were requested.
     */
    @JsonProperty("identifiers")
    public List<ConversationRowIdentifier> getIdentifiers() {
        return identifiers;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConversationRow && equalTo((ConversationRow) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConversationRow other) {
        return data.equals(other.data) && identifier.equals(other.identifier) && identifiers.equals(other.identifiers);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.data, this.identifier, this.identifiers);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Map<String, CellData> data = new LinkedHashMap<>();

        private Map<ConversationField, FieldValue> identifier = new LinkedHashMap<>();

        private List<ConversationRowIdentifier> identifiers = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ConversationRow other) {
            data(other.getData());
            identifier(other.getIdentifier());
            identifiers(other.getIdentifiers());
            return this;
        }

        /**
         * <p>The actual row data, where keys represent column headers and values contain the respective metric results.
         * A column the metric could not measure is absent from the map, so a row can carry fewer
         * entries than there are headers.</p>
         */
        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public Builder data(Map<String, CellData> data) {
            this.data.clear();
            if (data != null) {
                this.data.putAll(data);
            }
            return this;
        }

        public Builder putAllData(Map<String, CellData> data) {
            if (data != null) {
                this.data.putAll(data);
            }
            return this;
        }

        public Builder data(String key, CellData value) {
            this.data.put(key, value);
            return this;
        }

        /**
         * <p>Keyed by field, so it cannot represent two groupings that share a key - notably two
         * intelligent fields. Use <code>identifiers</code>, which carries one entry per grouping in request
         * order.</p>
         */
        @JsonSetter(value = "identifier", nulls = Nulls.SKIP)
        public Builder identifier(Map<ConversationField, FieldValue> identifier) {
            this.identifier.clear();
            if (identifier != null) {
                this.identifier.putAll(identifier);
            }
            return this;
        }

        public Builder putAllIdentifier(Map<ConversationField, FieldValue> identifier) {
            if (identifier != null) {
                this.identifier.putAll(identifier);
            }
            return this;
        }

        public Builder identifier(ConversationField key, FieldValue value) {
            this.identifier.put(key, value);
            return this;
        }

        /**
         * <p>One entry per grouping, in the order the groupings were requested.</p>
         */
        @JsonSetter(value = "identifiers", nulls = Nulls.SKIP)
        public Builder identifiers(List<ConversationRowIdentifier> identifiers) {
            this.identifiers.clear();
            if (identifiers != null) {
                this.identifiers.addAll(identifiers);
            }
            return this;
        }

        public Builder addIdentifiers(ConversationRowIdentifier identifiers) {
            this.identifiers.add(identifiers);
            return this;
        }

        public Builder addAllIdentifiers(List<ConversationRowIdentifier> identifiers) {
            if (identifiers != null) {
                this.identifiers.addAll(identifiers);
            }
            return this;
        }

        public ConversationRow build() {
            return new ConversationRow(data, identifier, identifiers, additionalProperties);
        }
    }
}
