/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.analytics.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mavenagi.core.ObjectMappers;
import com.mavenagi.resources.commons.types.EventField;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EventDistinctCount.Builder.class)
public final class EventDistinctCount {
    private final EventField targetField;

    private final Map<String, Object> additionalProperties;

    private EventDistinctCount(EventField targetField, Map<String, Object> additionalProperties) {
        this.targetField = targetField;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return All the distinct values of this field will be counted.
     */
    @JsonProperty("targetField")
    public EventField getTargetField() {
        return targetField;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EventDistinctCount && equalTo((EventDistinctCount) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EventDistinctCount other) {
        return targetField.equals(other.targetField);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.targetField);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TargetFieldStage builder() {
        return new Builder();
    }

    public interface TargetFieldStage {
        /**
         * <p>All the distinct values of this field will be counted.</p>
         */
        _FinalStage targetField(@NotNull EventField targetField);

        Builder from(EventDistinctCount other);
    }

    public interface _FinalStage {
        EventDistinctCount build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TargetFieldStage, _FinalStage {
        private EventField targetField;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EventDistinctCount other) {
            targetField(other.getTargetField());
            return this;
        }

        /**
         * <p>All the distinct values of this field will be counted.</p>
         * <p>All the distinct values of this field will be counted.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("targetField")
        public _FinalStage targetField(@NotNull EventField targetField) {
            this.targetField = Objects.requireNonNull(targetField, "targetField must not be null");
            return this;
        }

        @java.lang.Override
        public EventDistinctCount build() {
            return new EventDistinctCount(targetField, additionalProperties);
        }
    }
}
