/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.analytics.types;

import com.mavenagi.resources.commons.types.EventFilter;
import java.util.Optional;

public interface IEventAnalyticsRequest {
    Optional<EventFilter> getEventFilter();

    Optional<String> getTimezone();
}
