/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.charters;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.mavenagi.core.ClientOptions;
import com.mavenagi.core.MavenAGIApiException;
import com.mavenagi.core.MavenAGIException;
import com.mavenagi.core.MavenAGIHttpResponse;
import com.mavenagi.core.MediaTypes;
import com.mavenagi.core.ObjectMappers;
import com.mavenagi.core.QueryStringMapper;
import com.mavenagi.core.RequestOptions;
import com.mavenagi.resources.charters.requests.CharterDeleteRequest;
import com.mavenagi.resources.charters.requests.CharterGetAncestorsRequest;
import com.mavenagi.resources.charters.requests.CharterGetRequest;
import com.mavenagi.resources.charters.requests.CharterPatchRequest;
import com.mavenagi.resources.charters.types.CharterAncestorsResponse;
import com.mavenagi.resources.charters.types.CharterListChildrenRequest;
import com.mavenagi.resources.charters.types.CharterListChildrenResponse;
import com.mavenagi.resources.charters.types.CharterRequest;
import com.mavenagi.resources.charters.types.CharterResponse;
import com.mavenagi.resources.charters.types.CharterSearchRequest;
import com.mavenagi.resources.charters.types.CharterSearchResponse;
import com.mavenagi.resources.commons.errors.BadRequestError;
import com.mavenagi.resources.commons.errors.NotFoundError;
import com.mavenagi.resources.commons.errors.PayloadTooLargeError;
import com.mavenagi.resources.commons.errors.ServerError;
import com.mavenagi.resources.commons.errors.TooManyRequestsError;
import com.mavenagi.resources.commons.types.ErrorMessage;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawChartersClient {
    protected final ClientOptions clientOptions;

    public RawChartersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Create a new charter or update an existing one. Charters are governing
     * documents that combine a precondition (when the charter applies), a manual
     * (what the LLM should do), and the knowledge bases and actions the charter
     * makes available.
     * <p>All charters in an agent form a tree (forest / multi-roots). When a
     * charter is matched on a round, all its ancestor charters will be
     * incorporated. Non-leaf charters are referred to as a charter group.</p>
     * <p>Charters may specify a 0-indexed custom <code>userRank</code> that indicates
     * preferences among its siblings. The rank is currently only meaningful
     * for leaf charters as we enforce mutual exclusion among the leafs and
     * pick only the highest ranked (lowest numerical value) leaf to include in
     * the round. userRank may have gaps.</p>
     */
    public MavenAGIHttpResponse<CharterResponse> createOrUpdate(CharterRequest request) {
        return createOrUpdate(request, null);
    }

    /**
     * Create a new charter or update an existing one. Charters are governing
     * documents that combine a precondition (when the charter applies), a manual
     * (what the LLM should do), and the knowledge bases and actions the charter
     * makes available.
     * <p>All charters in an agent form a tree (forest / multi-roots). When a
     * charter is matched on a round, all its ancestor charters will be
     * incorporated. Non-leaf charters are referred to as a charter group.</p>
     * <p>Charters may specify a 0-indexed custom <code>userRank</code> that indicates
     * preferences among its siblings. The rank is currently only meaningful
     * for leaf charters as we enforce mutual exclusion among the leafs and
     * pick only the highest ranked (lowest numerical value) leaf to include in
     * the round. userRank may have gaps.</p>
     */
    public MavenAGIHttpResponse<CharterResponse> createOrUpdate(CharterRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/charters")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MavenAGIException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("PUT", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new MavenAGIHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CharterResponse.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 413:
                        throw new PayloadTooLargeError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 500:
                        throw new ServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new MavenAGIApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new MavenAGIException("Network error executing HTTP request", e);
        }
    }

    /**
     * Get a charter by its reference ID.
     */
    public MavenAGIHttpResponse<CharterResponse> get(String charterReferenceId) {
        return get(charterReferenceId, CharterGetRequest.builder().build());
    }

    /**
     * Get a charter by its reference ID.
     */
    public MavenAGIHttpResponse<CharterResponse> get(String charterReferenceId, CharterGetRequest request) {
        return get(charterReferenceId, request, null);
    }

    /**
     * Get a charter by its reference ID.
     */
    public MavenAGIHttpResponse<CharterResponse> get(
            String charterReferenceId, CharterGetRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/charters")
                .addPathSegment(charterReferenceId);
        if (request.getAppId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "appId", request.getAppId().get(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new MavenAGIHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CharterResponse.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 413:
                        throw new PayloadTooLargeError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 500:
                        throw new ServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new MavenAGIApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new MavenAGIException("Network error executing HTTP request", e);
        }
    }

    /**
     * Update mutable fields on a charter. Only provided fields are modified.
     * <p>To move a charter within the tree, set <code>parentCharterId</code>.
     * To promote to root level, set <code>parentCharterId</code> explicitly to null.</p>
     * <p><strong>Status behavior</strong>:</p>
     * <ul>
     * <li>Setting <code>status</code> to <code>INACTIVE</code> applies only to the targeted charter;
     * it does not cascade to descendants. However, its descendants will no
     * longer be incorporated at runtime.</li>
     * <li>Setting <code>status</code> to <code>ACTIVE</code> applies only to the targeted charter.
     * The caller is responsible for ensuring ancestor charters are also <code>ACTIVE</code>
     * if the full subtree should be reachable at runtime.</li>
     * </ul>
     * <p><strong>userRank conflict resolution</strong>: When <code>userRank</code> is set to a value already held by a
     * sibling, siblings at that rank and above are shifted up by 1 (like linked list semantics).
     * The caller does not need to manage uniqueness explicitly.</p>
     */
    public MavenAGIHttpResponse<CharterResponse> patch(String charterReferenceId) {
        return patch(charterReferenceId, CharterPatchRequest.builder().build());
    }

    /**
     * Update mutable fields on a charter. Only provided fields are modified.
     * <p>To move a charter within the tree, set <code>parentCharterId</code>.
     * To promote to root level, set <code>parentCharterId</code> explicitly to null.</p>
     * <p><strong>Status behavior</strong>:</p>
     * <ul>
     * <li>Setting <code>status</code> to <code>INACTIVE</code> applies only to the targeted charter;
     * it does not cascade to descendants. However, its descendants will no
     * longer be incorporated at runtime.</li>
     * <li>Setting <code>status</code> to <code>ACTIVE</code> applies only to the targeted charter.
     * The caller is responsible for ensuring ancestor charters are also <code>ACTIVE</code>
     * if the full subtree should be reachable at runtime.</li>
     * </ul>
     * <p><strong>userRank conflict resolution</strong>: When <code>userRank</code> is set to a value already held by a
     * sibling, siblings at that rank and above are shifted up by 1 (like linked list semantics).
     * The caller does not need to manage uniqueness explicitly.</p>
     */
    public MavenAGIHttpResponse<CharterResponse> patch(String charterReferenceId, CharterPatchRequest request) {
        return patch(charterReferenceId, request, null);
    }

    /**
     * Update mutable fields on a charter. Only provided fields are modified.
     * <p>To move a charter within the tree, set <code>parentCharterId</code>.
     * To promote to root level, set <code>parentCharterId</code> explicitly to null.</p>
     * <p><strong>Status behavior</strong>:</p>
     * <ul>
     * <li>Setting <code>status</code> to <code>INACTIVE</code> applies only to the targeted charter;
     * it does not cascade to descendants. However, its descendants will no
     * longer be incorporated at runtime.</li>
     * <li>Setting <code>status</code> to <code>ACTIVE</code> applies only to the targeted charter.
     * The caller is responsible for ensuring ancestor charters are also <code>ACTIVE</code>
     * if the full subtree should be reachable at runtime.</li>
     * </ul>
     * <p><strong>userRank conflict resolution</strong>: When <code>userRank</code> is set to a value already held by a
     * sibling, siblings at that rank and above are shifted up by 1 (like linked list semantics).
     * The caller does not need to manage uniqueness explicitly.</p>
     */
    public MavenAGIHttpResponse<CharterResponse> patch(
            String charterReferenceId, CharterPatchRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/charters")
                .addPathSegment(charterReferenceId)
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request),
                    MediaType.parse("application/merge-patch+json"));
        } catch (JsonProcessingException e) {
            throw new MavenAGIException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/merge-patch+json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new MavenAGIHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CharterResponse.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 413:
                        throw new PayloadTooLargeError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 500:
                        throw new ServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new MavenAGIApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new MavenAGIException("Network error executing HTTP request", e);
        }
    }

    /**
     * Delete a charter and all of its descendants recursively.
     * <p>The charter must be set to <code>INACTIVE</code> before it can be deleted. This prevents accidental
     * deletion of active charters. Descendant charters may be in any status — they will be
     * soft-deleted regardless.</p>
     * <p>Deleted charters are excluded from list results but can be retrieved by ID for archival purposes.</p>
     * <p>Deleted charters cannot be modified.</p>
     */
    public MavenAGIHttpResponse<CharterResponse> delete(String charterReferenceId) {
        return delete(charterReferenceId, CharterDeleteRequest.builder().build());
    }

    /**
     * Delete a charter and all of its descendants recursively.
     * <p>The charter must be set to <code>INACTIVE</code> before it can be deleted. This prevents accidental
     * deletion of active charters. Descendant charters may be in any status — they will be
     * soft-deleted regardless.</p>
     * <p>Deleted charters are excluded from list results but can be retrieved by ID for archival purposes.</p>
     * <p>Deleted charters cannot be modified.</p>
     */
    public MavenAGIHttpResponse<CharterResponse> delete(String charterReferenceId, CharterDeleteRequest request) {
        return delete(charterReferenceId, request, null);
    }

    /**
     * Delete a charter and all of its descendants recursively.
     * <p>The charter must be set to <code>INACTIVE</code> before it can be deleted. This prevents accidental
     * deletion of active charters. Descendant charters may be in any status — they will be
     * soft-deleted regardless.</p>
     * <p>Deleted charters are excluded from list results but can be retrieved by ID for archival purposes.</p>
     * <p>Deleted charters cannot be modified.</p>
     */
    public MavenAGIHttpResponse<CharterResponse> delete(
            String charterReferenceId, CharterDeleteRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/charters")
                .addPathSegment(charterReferenceId);
        if (request.getAppId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "appId", request.getAppId().get(), false);
        }
        if (request.getVariantReferenceId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "variantReferenceId",
                    request.getVariantReferenceId().get(),
                    false);
        }
        if (request.getVariantAppId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "variantAppId", request.getVariantAppId().get(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new MavenAGIHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CharterResponse.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 413:
                        throw new PayloadTooLargeError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 500:
                        throw new ServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new MavenAGIApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new MavenAGIException("Network error executing HTTP request", e);
        }
    }

    /**
     * Search for charters matching the provided filters. Supports filtering by
     * referenced action IDs and knowledge base IDs to find charters that make
     * specific context items available.
     * <p>Returns both ACTIVE and INACTIVE charters (DELETED charters are excluded).</p>
     * <p>Results are ordered by the <code>sort</code> field (defaults to CreatedAt). Use <code>sortDesc</code>
     * to control direction (defaults to descending). An empty filter list is
     * equivalent to omitting the field (no filter applied).</p>
     */
    public MavenAGIHttpResponse<CharterSearchResponse> search() {
        return search(CharterSearchRequest.builder().build());
    }

    /**
     * Search for charters matching the provided filters. Supports filtering by
     * referenced action IDs and knowledge base IDs to find charters that make
     * specific context items available.
     * <p>Returns both ACTIVE and INACTIVE charters (DELETED charters are excluded).</p>
     * <p>Results are ordered by the <code>sort</code> field (defaults to CreatedAt). Use <code>sortDesc</code>
     * to control direction (defaults to descending). An empty filter list is
     * equivalent to omitting the field (no filter applied).</p>
     */
    public MavenAGIHttpResponse<CharterSearchResponse> search(CharterSearchRequest request) {
        return search(request, null);
    }

    /**
     * Search for charters matching the provided filters. Supports filtering by
     * referenced action IDs and knowledge base IDs to find charters that make
     * specific context items available.
     * <p>Returns both ACTIVE and INACTIVE charters (DELETED charters are excluded).</p>
     * <p>Results are ordered by the <code>sort</code> field (defaults to CreatedAt). Use <code>sortDesc</code>
     * to control direction (defaults to descending). An empty filter list is
     * equivalent to omitting the field (no filter applied).</p>
     */
    public MavenAGIHttpResponse<CharterSearchResponse> search(
            CharterSearchRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/charters")
                .addPathSegments("search")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MavenAGIException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new MavenAGIHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CharterSearchResponse.class),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 413:
                        throw new PayloadTooLargeError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 500:
                        throw new ServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new MavenAGIApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new MavenAGIException("Network error executing HTTP request", e);
        }
    }

    /**
     * Return a flat list containing the specified charter and all of its ancestors
     * up to the root. Useful for rendering tree context around search results.
     * <p>Each entry is a full charter, so an ancestor's references and precondition are
     * readable without a follow-up request per level.</p>
     * <p>The list is always finite: charter hierarchies are acyclic, so a charter is never its own
     * ancestor and the walk to the root terminates.</p>
     * <p>Returns 404 if the charter does not exist or is deleted.</p>
     */
    public MavenAGIHttpResponse<CharterAncestorsResponse> getAncestors(String charterReferenceId) {
        return getAncestors(
                charterReferenceId, CharterGetAncestorsRequest.builder().build());
    }

    /**
     * Return a flat list containing the specified charter and all of its ancestors
     * up to the root. Useful for rendering tree context around search results.
     * <p>Each entry is a full charter, so an ancestor's references and precondition are
     * readable without a follow-up request per level.</p>
     * <p>The list is always finite: charter hierarchies are acyclic, so a charter is never its own
     * ancestor and the walk to the root terminates.</p>
     * <p>Returns 404 if the charter does not exist or is deleted.</p>
     */
    public MavenAGIHttpResponse<CharterAncestorsResponse> getAncestors(
            String charterReferenceId, CharterGetAncestorsRequest request) {
        return getAncestors(charterReferenceId, request, null);
    }

    /**
     * Return a flat list containing the specified charter and all of its ancestors
     * up to the root. Useful for rendering tree context around search results.
     * <p>Each entry is a full charter, so an ancestor's references and precondition are
     * readable without a follow-up request per level.</p>
     * <p>The list is always finite: charter hierarchies are acyclic, so a charter is never its own
     * ancestor and the walk to the root terminates.</p>
     * <p>Returns 404 if the charter does not exist or is deleted.</p>
     */
    public MavenAGIHttpResponse<CharterAncestorsResponse> getAncestors(
            String charterReferenceId, CharterGetAncestorsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/charters")
                .addPathSegment(charterReferenceId)
                .addPathSegments("ancestors");
        if (request.getAppId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "appId", request.getAppId().get(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new MavenAGIHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CharterAncestorsResponse.class),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 413:
                        throw new PayloadTooLargeError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 500:
                        throw new ServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new MavenAGIApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new MavenAGIException("Network error executing HTTP request", e);
        }
    }

    /**
     * Batch fetch direct children of the specified parent charters. Returns one
     * group per requested parent in the same order as parentIds, with grandchild
     * IDs populated on each child for expandability signals.
     * <p>Pass an empty parentIds list to fetch all root-level charters for the agent.
     * Intended to be used for easy BFS traversal, though calling with parents
     * at mixed levels are allowed. Roots and specific parents cannot be mixed
     * in one request.</p>
     * <p>DELETED charters are never returned.</p>
     */
    public MavenAGIHttpResponse<CharterListChildrenResponse> listChildren(CharterListChildrenRequest request) {
        return listChildren(request, null);
    }

    /**
     * Batch fetch direct children of the specified parent charters. Returns one
     * group per requested parent in the same order as parentIds, with grandchild
     * IDs populated on each child for expandability signals.
     * <p>Pass an empty parentIds list to fetch all root-level charters for the agent.
     * Intended to be used for easy BFS traversal, though calling with parents
     * at mixed levels are allowed. Roots and specific parents cannot be mixed
     * in one request.</p>
     * <p>DELETED charters are never returned.</p>
     */
    public MavenAGIHttpResponse<CharterListChildrenResponse> listChildren(
            CharterListChildrenRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/charters")
                .addPathSegments("list-children")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MavenAGIException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new MavenAGIHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CharterListChildrenResponse.class),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 413:
                        throw new PayloadTooLargeError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                    case 500:
                        throw new ServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new MavenAGIApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new MavenAGIException("Network error executing HTTP request", e);
        }
    }
}
