/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.appdirectory;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.mavenagi.core.ClientOptions;
import com.mavenagi.core.MavenAGIApiException;
import com.mavenagi.core.MavenAGIException;
import com.mavenagi.core.MavenAGIHttpResponse;
import com.mavenagi.core.MediaTypes;
import com.mavenagi.core.ObjectMappers;
import com.mavenagi.core.RequestOptions;
import com.mavenagi.resources.appdirectory.requests.GetAppSettingUploadUrlRequest;
import com.mavenagi.resources.appdirectory.types.DirectoryAppsSearchRequest;
import com.mavenagi.resources.appdirectory.types.GetDirectoryAppSettingDownloadUrlResponse;
import com.mavenagi.resources.appdirectory.types.GetDirectoryAppSettingUploadUrlResponse;
import com.mavenagi.resources.appdirectory.types.InstallDirectoryAppRequest;
import com.mavenagi.resources.commons.errors.BadRequestError;
import com.mavenagi.resources.commons.errors.NotFoundError;
import com.mavenagi.resources.commons.errors.PayloadTooLargeError;
import com.mavenagi.resources.commons.errors.ServerError;
import com.mavenagi.resources.commons.errors.TooManyRequestsError;
import com.mavenagi.resources.commons.types.ErrorMessage;
import com.mavenagi.resources.developerscommons.types.AppsResponse;
import com.mavenagi.resources.developerscommons.types.MarketplaceAppDetail;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawAppDirectoryClient {
    protected final ClientOptions clientOptions;

    public AsyncRawAppDirectoryClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Lists apps available to install on the agent, with filtering and pagination.
     */
    public CompletableFuture<MavenAGIHttpResponse<AppsResponse>> search() {
        return search(DirectoryAppsSearchRequest.builder().build());
    }

    /**
     * Lists apps available to install on the agent, with filtering and pagination.
     */
    public CompletableFuture<MavenAGIHttpResponse<AppsResponse>> search(DirectoryAppsSearchRequest request) {
        return search(request, null);
    }

    /**
     * Lists apps available to install on the agent, with filtering and pagination.
     */
    public CompletableFuture<MavenAGIHttpResponse<AppsResponse>> search(
            DirectoryAppsSearchRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/directory/search")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MavenAGIException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<MavenAGIHttpResponse<AppsResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new MavenAGIHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), AppsResponse.class),
                                response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 413:
                                future.completeExceptionally(new PayloadTooLargeError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new ServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new MavenAGIApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new MavenAGIException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MavenAGIException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Gets an app and its installation status for the agent.
     */
    public CompletableFuture<MavenAGIHttpResponse<MarketplaceAppDetail>> get(String appId) {
        return get(appId, null);
    }

    /**
     * Gets an app and its installation status for the agent.
     */
    public CompletableFuture<MavenAGIHttpResponse<MarketplaceAppDetail>> get(
            String appId, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/directory")
                .addPathSegment(appId)
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<MavenAGIHttpResponse<MarketplaceAppDetail>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new MavenAGIHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), MarketplaceAppDetail.class),
                                response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 413:
                                future.completeExceptionally(new PayloadTooLargeError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new ServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new MavenAGIApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new MavenAGIException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MavenAGIException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Installs the app on the agent, or updates settings for an existing installation. Re-runs the postInstall lifecycle hook on each call.
     */
    public CompletableFuture<MavenAGIHttpResponse<Void>> install(String appId, InstallDirectoryAppRequest request) {
        return install(appId, request, null);
    }

    /**
     * Installs the app on the agent, or updates settings for an existing installation. Re-runs the postInstall lifecycle hook on each call.
     */
    public CompletableFuture<MavenAGIHttpResponse<Void>> install(
            String appId, InstallDirectoryAppRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/directory")
                .addPathSegment(appId)
                .addPathSegments("install")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MavenAGIException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<MavenAGIHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new MavenAGIHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 413:
                                future.completeExceptionally(new PayloadTooLargeError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new ServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new MavenAGIApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new MavenAGIException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MavenAGIException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Uninstalls the app from the agent.
     */
    public CompletableFuture<MavenAGIHttpResponse<Void>> uninstall(String appId) {
        return uninstall(appId, null);
    }

    /**
     * Uninstalls the app from the agent.
     */
    public CompletableFuture<MavenAGIHttpResponse<Void>> uninstall(String appId, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/directory")
                .addPathSegment(appId)
                .addPathSegments("install")
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<MavenAGIHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new MavenAGIHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 413:
                                future.completeExceptionally(new PayloadTooLargeError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new ServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new MavenAGIApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new MavenAGIException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MavenAGIException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Gets a url for downloading a file app setting.
     */
    public CompletableFuture<MavenAGIHttpResponse<GetDirectoryAppSettingDownloadUrlResponse>> getSettingDownloadUrl(
            String appId, String settingsKey) {
        return getSettingDownloadUrl(appId, settingsKey, null);
    }

    /**
     * Gets a url for downloading a file app setting.
     */
    public CompletableFuture<MavenAGIHttpResponse<GetDirectoryAppSettingDownloadUrlResponse>> getSettingDownloadUrl(
            String appId, String settingsKey, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/directory")
                .addPathSegment(appId)
                .addPathSegments("settings")
                .addPathSegment(settingsKey)
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<MavenAGIHttpResponse<GetDirectoryAppSettingDownloadUrlResponse>> future =
                new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new MavenAGIHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBody.string(), GetDirectoryAppSettingDownloadUrlResponse.class),
                                response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 413:
                                future.completeExceptionally(new PayloadTooLargeError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new ServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new MavenAGIApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new MavenAGIException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MavenAGIException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Gets a presigned url for uploading a file app setting before installation.
     */
    public CompletableFuture<MavenAGIHttpResponse<GetDirectoryAppSettingUploadUrlResponse>> getSettingUploadUrl(
            String appId, String settingsKey, GetAppSettingUploadUrlRequest request) {
        return getSettingUploadUrl(appId, settingsKey, request, null);
    }

    /**
     * Gets a presigned url for uploading a file app setting before installation.
     */
    public CompletableFuture<MavenAGIHttpResponse<GetDirectoryAppSettingUploadUrlResponse>> getSettingUploadUrl(
            String appId, String settingsKey, GetAppSettingUploadUrlRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/directory")
                .addPathSegment(appId)
                .addPathSegments("settings")
                .addPathSegment(settingsKey)
                .addPathSegments("upload-url")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new MavenAGIException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<MavenAGIHttpResponse<GetDirectoryAppSettingUploadUrlResponse>> future =
                new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new MavenAGIHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBody.string(), GetDirectoryAppSettingUploadUrlResponse.class),
                                response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 413:
                                future.completeExceptionally(new PayloadTooLargeError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new ServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorMessage.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new MavenAGIApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new MavenAGIException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new MavenAGIException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
