/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.intelligentfields;

import com.mavenagi.core.ClientOptions;
import com.mavenagi.core.RequestOptions;
import com.mavenagi.resources.intelligentfields.requests.IntelligentFieldDeleteRequest;
import com.mavenagi.resources.intelligentfields.requests.IntelligentFieldGetRequest;
import com.mavenagi.resources.intelligentfields.requests.IntelligentFieldPatchRequest;
import com.mavenagi.resources.intelligentfields.types.IntelligentFieldDetailResponse;
import com.mavenagi.resources.intelligentfields.types.IntelligentFieldRequest;
import com.mavenagi.resources.intelligentfields.types.IntelligentFieldResponse;
import com.mavenagi.resources.intelligentfields.types.IntelligentFieldValueSearchRequest;
import com.mavenagi.resources.intelligentfields.types.IntelligentFieldValueSearchResponse;

public class IntelligentFieldsClient {
    protected final ClientOptions clientOptions;

    private final RawIntelligentFieldsClient rawClient;

    public IntelligentFieldsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawIntelligentFieldsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawIntelligentFieldsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Create a new intelligent field, or replace it if one already exists with the same
     * <code>fieldId.referenceId</code>. Intelligent fields hold LLM-generated values computed for
     * entities such as conversations.
     * <p>New fields are created with <code>status: INACTIVE</code> and are not evaluated until activated
     * with the patch endpoint. A new field created in a <code>variantId</code> starts <code>ACTIVE</code> instead,
     * since it is evaluated only once that variant is published and given traffic; it starts
     * <code>INACTIVE</code> while the agent is at its limit of active fields. <code>definition</code> is limited
     * to 5,000 characters.</p>
     * <p>A replace that names a <code>variantId</code> must keep the field's <code>validationType</code> as that
     * variant has it, or it is rejected with reason <code>INTELLIGENT_FIELD_TYPE_CHANGED</code>. To use
     * a different type, create a new field. A field deleted in the variant may be recreated
     * with any type.</p>
     */
    public IntelligentFieldResponse createOrUpdate(IntelligentFieldRequest request) {
        return this.rawClient.createOrUpdate(request).body();
    }

    /**
     * Create a new intelligent field, or replace it if one already exists with the same
     * <code>fieldId.referenceId</code>. Intelligent fields hold LLM-generated values computed for
     * entities such as conversations.
     * <p>New fields are created with <code>status: INACTIVE</code> and are not evaluated until activated
     * with the patch endpoint. A new field created in a <code>variantId</code> starts <code>ACTIVE</code> instead,
     * since it is evaluated only once that variant is published and given traffic; it starts
     * <code>INACTIVE</code> while the agent is at its limit of active fields. <code>definition</code> is limited
     * to 5,000 characters.</p>
     * <p>A replace that names a <code>variantId</code> must keep the field's <code>validationType</code> as that
     * variant has it, or it is rejected with reason <code>INTELLIGENT_FIELD_TYPE_CHANGED</code>. To use
     * a different type, create a new field. A field deleted in the variant may be recreated
     * with any type.</p>
     */
    public IntelligentFieldResponse createOrUpdate(IntelligentFieldRequest request, RequestOptions requestOptions) {
        return this.rawClient.createOrUpdate(request, requestOptions).body();
    }

    /**
     * Deprecated. Use <code>GET /v1/capabilities/INTELLIGENT_FIELD/{referenceId}</code>, which reads any
     * kind of capability the same way. It does not carry <code>referencingCharters</code>; search
     * charters to find the ones that reference a capability.
     * <p>Get an intelligent field by its supplied ID</p>
     */
    public IntelligentFieldDetailResponse get(String fieldReferenceId) {
        return this.rawClient.get(fieldReferenceId).body();
    }

    /**
     * Deprecated. Use <code>GET /v1/capabilities/INTELLIGENT_FIELD/{referenceId}</code>, which reads any
     * kind of capability the same way. It does not carry <code>referencingCharters</code>; search
     * charters to find the ones that reference a capability.
     * <p>Get an intelligent field by its supplied ID</p>
     */
    public IntelligentFieldDetailResponse get(String fieldReferenceId, IntelligentFieldGetRequest request) {
        return this.rawClient.get(fieldReferenceId, request).body();
    }

    /**
     * Deprecated. Use <code>GET /v1/capabilities/INTELLIGENT_FIELD/{referenceId}</code>, which reads any
     * kind of capability the same way. It does not carry <code>referencingCharters</code>; search
     * charters to find the ones that reference a capability.
     * <p>Get an intelligent field by its supplied ID</p>
     */
    public IntelligentFieldDetailResponse get(
            String fieldReferenceId, IntelligentFieldGetRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(fieldReferenceId, request, requestOptions).body();
    }

    /**
     * Update the mutable properties of an intelligent field. Only the properties present in
     * the request body are changed.
     * <p>This is also how a field is activated and deactivated: set <code>status</code> to <code>ACTIVE</code> to
     * start evaluating it, or <code>INACTIVE</code> to stop. <code>name</code>, <code>entityType</code>, and <code>validationType</code>
     * cannot be changed after creation.</p>
     */
    public IntelligentFieldResponse patch(String fieldReferenceId) {
        return this.rawClient.patch(fieldReferenceId).body();
    }

    /**
     * Update the mutable properties of an intelligent field. Only the properties present in
     * the request body are changed.
     * <p>This is also how a field is activated and deactivated: set <code>status</code> to <code>ACTIVE</code> to
     * start evaluating it, or <code>INACTIVE</code> to stop. <code>name</code>, <code>entityType</code>, and <code>validationType</code>
     * cannot be changed after creation.</p>
     */
    public IntelligentFieldResponse patch(String fieldReferenceId, IntelligentFieldPatchRequest request) {
        return this.rawClient.patch(fieldReferenceId, request).body();
    }

    /**
     * Update the mutable properties of an intelligent field. Only the properties present in
     * the request body are changed.
     * <p>This is also how a field is activated and deactivated: set <code>status</code> to <code>ACTIVE</code> to
     * start evaluating it, or <code>INACTIVE</code> to stop. <code>name</code>, <code>entityType</code>, and <code>validationType</code>
     * cannot be changed after creation.</p>
     */
    public IntelligentFieldResponse patch(
            String fieldReferenceId, IntelligentFieldPatchRequest request, RequestOptions requestOptions) {
        return this.rawClient.patch(fieldReferenceId, request, requestOptions).body();
    }

    /**
     * Deprecated. Use <code>DELETE /v1/capabilities/INTELLIGENT_FIELD/{referenceId}</code>, which
     * deletes any kind of capability the same way. That endpoint returns no body.
     * <p>Soft delete an intelligent field. Only INACTIVE fields can be deleted.</p>
     * <p>Deleted fields are excluded from search results but can still be retrieved by ID.
     * Creating a new field with the same referenceId as a deleted field will overwrite
     * the deleted field and restore it with the status a new field gets.</p>
     * <p>Deleted fields cannot be modified.</p>
     */
    public IntelligentFieldResponse delete(String fieldReferenceId) {
        return this.rawClient.delete(fieldReferenceId).body();
    }

    /**
     * Deprecated. Use <code>DELETE /v1/capabilities/INTELLIGENT_FIELD/{referenceId}</code>, which
     * deletes any kind of capability the same way. That endpoint returns no body.
     * <p>Soft delete an intelligent field. Only INACTIVE fields can be deleted.</p>
     * <p>Deleted fields are excluded from search results but can still be retrieved by ID.
     * Creating a new field with the same referenceId as a deleted field will overwrite
     * the deleted field and restore it with the status a new field gets.</p>
     * <p>Deleted fields cannot be modified.</p>
     */
    public IntelligentFieldResponse delete(String fieldReferenceId, IntelligentFieldDeleteRequest request) {
        return this.rawClient.delete(fieldReferenceId, request).body();
    }

    /**
     * Deprecated. Use <code>DELETE /v1/capabilities/INTELLIGENT_FIELD/{referenceId}</code>, which
     * deletes any kind of capability the same way. That endpoint returns no body.
     * <p>Soft delete an intelligent field. Only INACTIVE fields can be deleted.</p>
     * <p>Deleted fields are excluded from search results but can still be retrieved by ID.
     * Creating a new field with the same referenceId as a deleted field will overwrite
     * the deleted field and restore it with the status a new field gets.</p>
     * <p>Deleted fields cannot be modified.</p>
     */
    public IntelligentFieldResponse delete(
            String fieldReferenceId, IntelligentFieldDeleteRequest request, RequestOptions requestOptions) {
        return this.rawClient.delete(fieldReferenceId, request, requestOptions).body();
    }

    /**
     * Search the values that have been computed for intelligent fields, across entities.
     * Supports filtering by properties of the field, by target entity, and by when the
     * value was computed.
     * <p>Values only exist for fields that were ACTIVE when the entity was evaluated, so a
     * newly activated field returns nothing until evaluation has run.</p>
     */
    public IntelligentFieldValueSearchResponse searchValues() {
        return this.rawClient.searchValues().body();
    }

    /**
     * Search the values that have been computed for intelligent fields, across entities.
     * Supports filtering by properties of the field, by target entity, and by when the
     * value was computed.
     * <p>Values only exist for fields that were ACTIVE when the entity was evaluated, so a
     * newly activated field returns nothing until evaluation has run.</p>
     */
    public IntelligentFieldValueSearchResponse searchValues(IntelligentFieldValueSearchRequest request) {
        return this.rawClient.searchValues(request).body();
    }

    /**
     * Search the values that have been computed for intelligent fields, across entities.
     * Supports filtering by properties of the field, by target entity, and by when the
     * value was computed.
     * <p>Values only exist for fields that were ACTIVE when the entity was evaluated, so a
     * newly activated field returns nothing until evaluation has run.</p>
     */
    public IntelligentFieldValueSearchResponse searchValues(
            IntelligentFieldValueSearchRequest request, RequestOptions requestOptions) {
        return this.rawClient.searchValues(request, requestOptions).body();
    }
}
