/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.segments.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mavenagi.core.ObjectMappers;
import com.mavenagi.resources.commons.types.EntityId;
import com.mavenagi.resources.commons.types.PreconditionResponse;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SegmentSummary.Builder.class)
public final class SegmentSummary {
    private final EntityId segmentId;

    private final String name;

    private final SegmentStatus status;

    private final PreconditionResponse precondition;

    private final Map<String, Object> additionalProperties;

    private SegmentSummary(
            EntityId segmentId,
            String name,
            SegmentStatus status,
            PreconditionResponse precondition,
            Map<String, Object> additionalProperties) {
        this.segmentId = segmentId;
        this.name = name;
        this.status = status;
        this.precondition = precondition;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return ID that uniquely identifies this segment.
     */
    @JsonProperty("segmentId")
    public EntityId getSegmentId() {
        return segmentId;
    }

    /**
     * @return The display name of the segment.
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return The lifecycle status of the segment.
     */
    @JsonProperty("status")
    public SegmentStatus getStatus() {
        return status;
    }

    /**
     * @return The precondition that must be met for a conversation message to match this segment.
     */
    @JsonProperty("precondition")
    public PreconditionResponse getPrecondition() {
        return precondition;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SegmentSummary && equalTo((SegmentSummary) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SegmentSummary other) {
        return segmentId.equals(other.segmentId)
                && name.equals(other.name)
                && status.equals(other.status)
                && precondition.equals(other.precondition);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.segmentId, this.name, this.status, this.precondition);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SegmentIdStage builder() {
        return new Builder();
    }

    public interface SegmentIdStage {
        /**
         * <p>ID that uniquely identifies this segment.</p>
         */
        NameStage segmentId(@NotNull EntityId segmentId);

        Builder from(SegmentSummary other);
    }

    public interface NameStage {
        /**
         * <p>The display name of the segment.</p>
         */
        StatusStage name(@NotNull String name);
    }

    public interface StatusStage {
        /**
         * <p>The lifecycle status of the segment.</p>
         */
        PreconditionStage status(@NotNull SegmentStatus status);
    }

    public interface PreconditionStage {
        /**
         * <p>The precondition that must be met for a conversation message to match this segment.</p>
         */
        _FinalStage precondition(@NotNull PreconditionResponse precondition);
    }

    public interface _FinalStage {
        SegmentSummary build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements SegmentIdStage, NameStage, StatusStage, PreconditionStage, _FinalStage {
        private EntityId segmentId;

        private String name;

        private SegmentStatus status;

        private PreconditionResponse precondition;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SegmentSummary other) {
            segmentId(other.getSegmentId());
            name(other.getName());
            status(other.getStatus());
            precondition(other.getPrecondition());
            return this;
        }

        /**
         * <p>ID that uniquely identifies this segment.</p>
         * <p>ID that uniquely identifies this segment.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("segmentId")
        public NameStage segmentId(@NotNull EntityId segmentId) {
            this.segmentId = Objects.requireNonNull(segmentId, "segmentId must not be null");
            return this;
        }

        /**
         * <p>The display name of the segment.</p>
         * <p>The display name of the segment.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public StatusStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>The lifecycle status of the segment.</p>
         * <p>The lifecycle status of the segment.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public PreconditionStage status(@NotNull SegmentStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        /**
         * <p>The precondition that must be met for a conversation message to match this segment.</p>
         * <p>The precondition that must be met for a conversation message to match this segment.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("precondition")
        public _FinalStage precondition(@NotNull PreconditionResponse precondition) {
            this.precondition = Objects.requireNonNull(precondition, "precondition must not be null");
            return this;
        }

        @java.lang.Override
        public SegmentSummary build() {
            return new SegmentSummary(segmentId, name, status, precondition, additionalProperties);
        }
    }
}
