/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.intelligentfields.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mavenagi.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IntelligentFieldDeleteRequest.Builder.class)
public final class IntelligentFieldDeleteRequest {
    private final Optional<String> appId;

    private final Optional<String> variantReferenceId;

    private final Optional<String> variantAppId;

    private final Map<String, Object> additionalProperties;

    private IntelligentFieldDeleteRequest(
            Optional<String> appId,
            Optional<String> variantReferenceId,
            Optional<String> variantAppId,
            Map<String, Object> additionalProperties) {
        this.appId = appId;
        this.variantReferenceId = variantReferenceId;
        this.variantAppId = variantAppId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The App ID of the intelligent field to delete. If not provided, the ID of the calling app will be used.
     */
    @JsonProperty("appId")
    public Optional<String> getAppId() {
        return appId;
    }

    /**
     * @return The agent variant reference ID of the intelligent field to delete.
     */
    @JsonProperty("variantReferenceId")
    public Optional<String> getVariantReferenceId() {
        return variantReferenceId;
    }

    /**
     * @return The App ID of the agent variant reference for the intelligent field to delete. If not provided, the ID of the calling app will be used.
     */
    @JsonProperty("variantAppId")
    public Optional<String> getVariantAppId() {
        return variantAppId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IntelligentFieldDeleteRequest && equalTo((IntelligentFieldDeleteRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IntelligentFieldDeleteRequest other) {
        return appId.equals(other.appId)
                && variantReferenceId.equals(other.variantReferenceId)
                && variantAppId.equals(other.variantAppId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.appId, this.variantReferenceId, this.variantAppId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> appId = Optional.empty();

        private Optional<String> variantReferenceId = Optional.empty();

        private Optional<String> variantAppId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(IntelligentFieldDeleteRequest other) {
            appId(other.getAppId());
            variantReferenceId(other.getVariantReferenceId());
            variantAppId(other.getVariantAppId());
            return this;
        }

        /**
         * <p>The App ID of the intelligent field to delete. If not provided, the ID of the calling app will be used.</p>
         */
        @JsonSetter(value = "appId", nulls = Nulls.SKIP)
        public Builder appId(Optional<String> appId) {
            this.appId = appId;
            return this;
        }

        public Builder appId(String appId) {
            this.appId = Optional.ofNullable(appId);
            return this;
        }

        /**
         * <p>The agent variant reference ID of the intelligent field to delete.</p>
         */
        @JsonSetter(value = "variantReferenceId", nulls = Nulls.SKIP)
        public Builder variantReferenceId(Optional<String> variantReferenceId) {
            this.variantReferenceId = variantReferenceId;
            return this;
        }

        public Builder variantReferenceId(String variantReferenceId) {
            this.variantReferenceId = Optional.ofNullable(variantReferenceId);
            return this;
        }

        /**
         * <p>The App ID of the agent variant reference for the intelligent field to delete. If not provided, the ID of the calling app will be used.</p>
         */
        @JsonSetter(value = "variantAppId", nulls = Nulls.SKIP)
        public Builder variantAppId(Optional<String> variantAppId) {
            this.variantAppId = variantAppId;
            return this;
        }

        public Builder variantAppId(String variantAppId) {
            this.variantAppId = Optional.ofNullable(variantAppId);
            return this;
        }

        public IntelligentFieldDeleteRequest build() {
            return new IntelligentFieldDeleteRequest(appId, variantReferenceId, variantAppId, additionalProperties);
        }
    }
}
