/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.knowledge.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mavenagi.core.ObjectMappers;
import com.mavenagi.resources.commons.types.LlmInclusionStatus;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = KnowledgeBaseFilter.Builder.class)
public final class KnowledgeBaseFilter {
    private final Optional<String> search;

    private final Optional<String> title;

    private final Optional<OffsetDateTime> createdAfter;

    private final Optional<OffsetDateTime> createdBefore;

    private final Optional<List<String>> appIds;

    private final Optional<List<KnowledgeBaseVersionStatus>> mostRecentVersionStatus;

    private final Optional<LlmInclusionStatus> llmInclusionStatus;

    private final Map<String, Object> additionalProperties;

    private KnowledgeBaseFilter(
            Optional<String> search,
            Optional<String> title,
            Optional<OffsetDateTime> createdAfter,
            Optional<OffsetDateTime> createdBefore,
            Optional<List<String>> appIds,
            Optional<List<KnowledgeBaseVersionStatus>> mostRecentVersionStatus,
            Optional<LlmInclusionStatus> llmInclusionStatus,
            Map<String, Object> additionalProperties) {
        this.search = search;
        this.title = title;
        this.createdAfter = createdAfter;
        this.createdBefore = createdBefore;
        this.appIds = appIds;
        this.mostRecentVersionStatus = mostRecentVersionStatus;
        this.llmInclusionStatus = llmInclusionStatus;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Full-text search query for matching knowledge bases by content.
     * When you search with this parameter, you're performing a full-text search across the knowledge title, tags and metadata.
     * <p>This field also supports a syntax for advanced filtering the <code>metadata</code> field.</p>
     * <p>Metadata examples:</p>
     * <ul>
     * <li><code>metadata:myvalue</code> - matches knowledge bases with any metadata field set to <code>myvalue</code></li>
     * <li><code>metadata.mykey:myvalue</code> - matches knowledge bases with a metadata field <code>mykey</code> set to <code>myvalue</code></li>
     * <li><code>metadata.mykey:myvalue OR anothervalue</code> - matches knowledge bases with a metadata field <code>mykey</code> set to <code>myvalue</code> or <code>anothervalue</code></li>
     * <li><code>metadata.mykey:*</code> - matches knowledge bases with a metadata field <code>mykey</code></li>
     * <li><code>-metadata:myvalue</code> - matches knowledge bases that do not have any metadata field set to <code>myvalue</code></li>
     * <li><code>_exists_:metadata</code> - matches knowledge bases that have any metadata field set</li>
     * </ul>
     */
    @JsonProperty("search")
    public Optional<String> getSearch() {
        return search;
    }

    /**
     * @return Filter by title
     */
    @JsonProperty("title")
    public Optional<String> getTitle() {
        return title;
    }

    /**
     * @return Filter knowledge bases created on or after this timestamp
     */
    @JsonProperty("createdAfter")
    public Optional<OffsetDateTime> getCreatedAfter() {
        return createdAfter;
    }

    /**
     * @return Filter knowledge bases created on or before this timestamp
     */
    @JsonProperty("createdBefore")
    public Optional<OffsetDateTime> getCreatedBefore() {
        return createdBefore;
    }

    /**
     * @return Filter by app IDs
     */
    @JsonProperty("appIds")
    public Optional<List<String>> getAppIds() {
        return appIds;
    }

    /**
     * @return Filter knowledge bases by the most recent version status
     */
    @JsonProperty("mostRecentVersionStatus")
    public Optional<List<KnowledgeBaseVersionStatus>> getMostRecentVersionStatus() {
        return mostRecentVersionStatus;
    }

    /**
     * @return Filter knowledge bases by the LLM inclusion status
     */
    @JsonProperty("llmInclusionStatus")
    public Optional<LlmInclusionStatus> getLlmInclusionStatus() {
        return llmInclusionStatus;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof KnowledgeBaseFilter && equalTo((KnowledgeBaseFilter) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(KnowledgeBaseFilter other) {
        return search.equals(other.search)
                && title.equals(other.title)
                && createdAfter.equals(other.createdAfter)
                && createdBefore.equals(other.createdBefore)
                && appIds.equals(other.appIds)
                && mostRecentVersionStatus.equals(other.mostRecentVersionStatus)
                && llmInclusionStatus.equals(other.llmInclusionStatus);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.search,
                this.title,
                this.createdAfter,
                this.createdBefore,
                this.appIds,
                this.mostRecentVersionStatus,
                this.llmInclusionStatus);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> search = Optional.empty();

        private Optional<String> title = Optional.empty();

        private Optional<OffsetDateTime> createdAfter = Optional.empty();

        private Optional<OffsetDateTime> createdBefore = Optional.empty();

        private Optional<List<String>> appIds = Optional.empty();

        private Optional<List<KnowledgeBaseVersionStatus>> mostRecentVersionStatus = Optional.empty();

        private Optional<LlmInclusionStatus> llmInclusionStatus = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(KnowledgeBaseFilter other) {
            search(other.getSearch());
            title(other.getTitle());
            createdAfter(other.getCreatedAfter());
            createdBefore(other.getCreatedBefore());
            appIds(other.getAppIds());
            mostRecentVersionStatus(other.getMostRecentVersionStatus());
            llmInclusionStatus(other.getLlmInclusionStatus());
            return this;
        }

        /**
         * <p>Full-text search query for matching knowledge bases by content.
         * When you search with this parameter, you're performing a full-text search across the knowledge title, tags and metadata.</p>
         * <p>This field also supports a syntax for advanced filtering the <code>metadata</code> field.</p>
         * <p>Metadata examples:</p>
         * <ul>
         * <li><code>metadata:myvalue</code> - matches knowledge bases with any metadata field set to <code>myvalue</code></li>
         * <li><code>metadata.mykey:myvalue</code> - matches knowledge bases with a metadata field <code>mykey</code> set to <code>myvalue</code></li>
         * <li><code>metadata.mykey:myvalue OR anothervalue</code> - matches knowledge bases with a metadata field <code>mykey</code> set to <code>myvalue</code> or <code>anothervalue</code></li>
         * <li><code>metadata.mykey:*</code> - matches knowledge bases with a metadata field <code>mykey</code></li>
         * <li><code>-metadata:myvalue</code> - matches knowledge bases that do not have any metadata field set to <code>myvalue</code></li>
         * <li><code>_exists_:metadata</code> - matches knowledge bases that have any metadata field set</li>
         * </ul>
         */
        @JsonSetter(value = "search", nulls = Nulls.SKIP)
        public Builder search(Optional<String> search) {
            this.search = search;
            return this;
        }

        public Builder search(String search) {
            this.search = Optional.ofNullable(search);
            return this;
        }

        /**
         * <p>Filter by title</p>
         */
        @JsonSetter(value = "title", nulls = Nulls.SKIP)
        public Builder title(Optional<String> title) {
            this.title = title;
            return this;
        }

        public Builder title(String title) {
            this.title = Optional.ofNullable(title);
            return this;
        }

        /**
         * <p>Filter knowledge bases created on or after this timestamp</p>
         */
        @JsonSetter(value = "createdAfter", nulls = Nulls.SKIP)
        public Builder createdAfter(Optional<OffsetDateTime> createdAfter) {
            this.createdAfter = createdAfter;
            return this;
        }

        public Builder createdAfter(OffsetDateTime createdAfter) {
            this.createdAfter = Optional.ofNullable(createdAfter);
            return this;
        }

        /**
         * <p>Filter knowledge bases created on or before this timestamp</p>
         */
        @JsonSetter(value = "createdBefore", nulls = Nulls.SKIP)
        public Builder createdBefore(Optional<OffsetDateTime> createdBefore) {
            this.createdBefore = createdBefore;
            return this;
        }

        public Builder createdBefore(OffsetDateTime createdBefore) {
            this.createdBefore = Optional.ofNullable(createdBefore);
            return this;
        }

        /**
         * <p>Filter by app IDs</p>
         */
        @JsonSetter(value = "appIds", nulls = Nulls.SKIP)
        public Builder appIds(Optional<List<String>> appIds) {
            this.appIds = appIds;
            return this;
        }

        public Builder appIds(List<String> appIds) {
            this.appIds = Optional.ofNullable(appIds);
            return this;
        }

        /**
         * <p>Filter knowledge bases by the most recent version status</p>
         */
        @JsonSetter(value = "mostRecentVersionStatus", nulls = Nulls.SKIP)
        public Builder mostRecentVersionStatus(Optional<List<KnowledgeBaseVersionStatus>> mostRecentVersionStatus) {
            this.mostRecentVersionStatus = mostRecentVersionStatus;
            return this;
        }

        public Builder mostRecentVersionStatus(List<KnowledgeBaseVersionStatus> mostRecentVersionStatus) {
            this.mostRecentVersionStatus = Optional.ofNullable(mostRecentVersionStatus);
            return this;
        }

        /**
         * <p>Filter knowledge bases by the LLM inclusion status</p>
         */
        @JsonSetter(value = "llmInclusionStatus", nulls = Nulls.SKIP)
        public Builder llmInclusionStatus(Optional<LlmInclusionStatus> llmInclusionStatus) {
            this.llmInclusionStatus = llmInclusionStatus;
            return this;
        }

        public Builder llmInclusionStatus(LlmInclusionStatus llmInclusionStatus) {
            this.llmInclusionStatus = Optional.ofNullable(llmInclusionStatus);
            return this;
        }

        public KnowledgeBaseFilter build() {
            return new KnowledgeBaseFilter(
                    search,
                    title,
                    createdAfter,
                    createdBefore,
                    appIds,
                    mostRecentVersionStatus,
                    llmInclusionStatus,
                    additionalProperties);
        }
    }
}
