/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.knowledge.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class KnowledgeDocumentStatus {
    public static final KnowledgeDocumentStatus IN_PROGRESS =
            new KnowledgeDocumentStatus(Value.IN_PROGRESS, "IN_PROGRESS");

    public static final KnowledgeDocumentStatus SUCCEEDED = new KnowledgeDocumentStatus(Value.SUCCEEDED, "SUCCEEDED");

    private final Value value;

    private final String string;

    KnowledgeDocumentStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof KnowledgeDocumentStatus
                        && this.string.equals(((KnowledgeDocumentStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case IN_PROGRESS:
                return visitor.visitInProgress();
            case SUCCEEDED:
                return visitor.visitSucceeded();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static KnowledgeDocumentStatus valueOf(String value) {
        switch (value) {
            case "IN_PROGRESS":
                return IN_PROGRESS;
            case "SUCCEEDED":
                return SUCCEEDED;
            default:
                return new KnowledgeDocumentStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SUCCEEDED,

        IN_PROGRESS,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSucceeded();

        T visitInProgress();

        T visitUnknown(String unknownType);
    }
}
