/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.knowledge.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mavenagi.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = KnowledgeBaseVersionProgress.Builder.class)
public final class KnowledgeBaseVersionProgress {
    private final String message;

    private final Optional<Long> completedCount;

    private final Optional<Long> totalCount;

    private final Map<String, Object> additionalProperties;

    private KnowledgeBaseVersionProgress(
            String message,
            Optional<Long> completedCount,
            Optional<Long> totalCount,
            Map<String, Object> additionalProperties) {
        this.message = message;
        this.completedCount = completedCount;
        this.totalCount = totalCount;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A user-facing message describing what the refresh is currently doing.
     */
    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    /**
     * @return How many units of work the refresh has finished so far. The numerator of a progress bar.
     * Must be supplied together with <code>totalCount</code>.
     */
    @JsonProperty("completedCount")
    public Optional<Long> getCompletedCount() {
        return completedCount;
    }

    /**
     * @return How many units of work the refresh expects in total. The denominator of a progress bar.
     * Must be supplied together with <code>completedCount</code>. Apps may revise this as a refresh
     * discovers more work.
     */
    @JsonProperty("totalCount")
    public Optional<Long> getTotalCount() {
        return totalCount;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof KnowledgeBaseVersionProgress && equalTo((KnowledgeBaseVersionProgress) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(KnowledgeBaseVersionProgress other) {
        return message.equals(other.message)
                && completedCount.equals(other.completedCount)
                && totalCount.equals(other.totalCount);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.message, this.completedCount, this.totalCount);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static MessageStage builder() {
        return new Builder();
    }

    public interface MessageStage {
        /**
         * <p>A user-facing message describing what the refresh is currently doing.</p>
         */
        _FinalStage message(@NotNull String message);

        Builder from(KnowledgeBaseVersionProgress other);
    }

    public interface _FinalStage {
        KnowledgeBaseVersionProgress build();

        /**
         * <p>How many units of work the refresh has finished so far. The numerator of a progress bar.
         * Must be supplied together with <code>totalCount</code>.</p>
         */
        _FinalStage completedCount(Optional<Long> completedCount);

        _FinalStage completedCount(Long completedCount);

        /**
         * <p>How many units of work the refresh expects in total. The denominator of a progress bar.
         * Must be supplied together with <code>completedCount</code>. Apps may revise this as a refresh
         * discovers more work.</p>
         */
        _FinalStage totalCount(Optional<Long> totalCount);

        _FinalStage totalCount(Long totalCount);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements MessageStage, _FinalStage {
        private String message;

        private Optional<Long> totalCount = Optional.empty();

        private Optional<Long> completedCount = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(KnowledgeBaseVersionProgress other) {
            message(other.getMessage());
            completedCount(other.getCompletedCount());
            totalCount(other.getTotalCount());
            return this;
        }

        /**
         * <p>A user-facing message describing what the refresh is currently doing.</p>
         * <p>A user-facing message describing what the refresh is currently doing.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("message")
        public _FinalStage message(@NotNull String message) {
            this.message = Objects.requireNonNull(message, "message must not be null");
            return this;
        }

        /**
         * <p>How many units of work the refresh expects in total. The denominator of a progress bar.
         * Must be supplied together with <code>completedCount</code>. Apps may revise this as a refresh
         * discovers more work.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage totalCount(Long totalCount) {
            this.totalCount = Optional.ofNullable(totalCount);
            return this;
        }

        /**
         * <p>How many units of work the refresh expects in total. The denominator of a progress bar.
         * Must be supplied together with <code>completedCount</code>. Apps may revise this as a refresh
         * discovers more work.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "totalCount", nulls = Nulls.SKIP)
        public _FinalStage totalCount(Optional<Long> totalCount) {
            this.totalCount = totalCount;
            return this;
        }

        /**
         * <p>How many units of work the refresh has finished so far. The numerator of a progress bar.
         * Must be supplied together with <code>totalCount</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage completedCount(Long completedCount) {
            this.completedCount = Optional.ofNullable(completedCount);
            return this;
        }

        /**
         * <p>How many units of work the refresh has finished so far. The numerator of a progress bar.
         * Must be supplied together with <code>totalCount</code>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "completedCount", nulls = Nulls.SKIP)
        public _FinalStage completedCount(Optional<Long> completedCount) {
            this.completedCount = completedCount;
            return this;
        }

        @java.lang.Override
        public KnowledgeBaseVersionProgress build() {
            return new KnowledgeBaseVersionProgress(message, completedCount, totalCount, additionalProperties);
        }
    }
}
