/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.api.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum FeedbackType {
    THUMBS_UP("THUMBS_UP"),

    THUMBS_DOWN("THUMBS_DOWN"),

    INSERT("INSERT"),

    HANDOFF("HANDOFF");

    private final String value;

    FeedbackType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
