/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.api.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum InboxItemStatus {
    OPEN("OPEN"),

    USER_RESOLVED("USER_RESOLVED"),

    SYSTEM_RESOLVED("SYSTEM_RESOLVED"),

    REGRESSED("REGRESSED"),

    IGNORED("IGNORED");

    private final String value;

    InboxItemStatus(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
