/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.translations;

import com.mavenagi.core.ClientOptions;
import com.mavenagi.core.RequestOptions;
import com.mavenagi.resources.translations.types.TranslationRequest;
import com.mavenagi.resources.translations.types.TranslationResponse;

public class TranslationsClient {
    protected final ClientOptions clientOptions;

    private final RawTranslationsClient rawClient;

    public TranslationsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawTranslationsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawTranslationsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Translate text from one language to another
     */
    public TranslationResponse translate(TranslationRequest request) {
        return this.rawClient.translate(request).body();
    }

    /**
     * Translate text from one language to another
     */
    public TranslationResponse translate(TranslationRequest request, RequestOptions requestOptions) {
        return this.rawClient.translate(request, requestOptions).body();
    }
}
