/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.api.resources.analyticscommons.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum TimeInterval {
    HOUR("HOUR"),

    DAY("DAY"),

    WEEK("WEEK"),

    MONTH("MONTH"),

    YEAR("YEAR");

    private final String value;

    TimeInterval(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
