/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.agents.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum PiiCategory {
    NAME("Name"),

    EMAIL("Email"),

    PHONE_NUMBER("PhoneNumber"),

    STREET_ADDRESS("StreetAddress"),

    CREDIT_CARD_NUMBER("CreditCardNumber"),

    US_BANK_ACCOUNT_NUMBER("UsBankAccountNumber"),

    US_SOCIAL_SECURITY_NUMBER("UsSocialSecurityNumber"),

    US_UK_PASSPORT_NUMBER("UsUkPassportNumber"),

    US_DRIVERS_LICENSE_NUMBER("UsDriversLicenseNumber"),

    DATE("Date"),

    IP_ADDRESS("IpAddress"),

    URL("Url"),

    ABA_ROUTING_NUMBER("AbaRoutingNumber"),

    AGE("Age"),

    SWIFT_CODE("SwiftCode"),

    AU_BANK_ACCOUNT_NUMBER("AuBankAccountNumber"),

    AU_BUSINESS_NUMBER("AuBusinessNumber"),

    AU_COMPANY_NUMBER("AuCompanyNumber"),

    AU_DRIVERS_LICENSE_NUMBER("AuDriversLicenseNumber"),

    AU_MEDICAL_ACCOUNT_NUMBER("AuMedicalAccountNumber"),

    AU_PASSPORT_NUMBER("AuPassportNumber"),

    AU_TAX_FILE_NUMBER("AuTaxFileNumber"),

    CA_BANK_ACCOUNT_NUMBER("CaBankAccountNumber"),

    CA_DRIVERS_LICENSE_NUMBER("CaDriversLicenseNumber"),

    CA_HEALTH_SERVICE_NUMBER("CaHealthServiceNumber"),

    CA_PASSPORT_NUMBER("CaPassportNumber"),

    CA_PERSONAL_HEALTH_IDENTIFICATION("CaPersonalHealthIdentification"),

    CA_SOCIAL_INSURANCE_NUMBER("CaSocialInsuranceNumber"),

    ES_DNI("EsDni"),

    ES_SOCIAL_SECURITY_NUMBER("EsSocialSecurityNumber"),

    ES_TAX_IDENTIFICATION_NUMBER("EsTaxIdentificationNumber"),

    EU_DEBIT_CARD_NUMBER("EuDebitCardNumber"),

    EU_DRIVERS_LICENSE_NUMBER("EuDriversLicenseNumber"),

    EU_GPS_COORDINATES("EuGpsCoordinates"),

    EU_NATIONAL_IDENTIFICATION_NUMBER("EuNationalIdentificationNumber"),

    EU_PASSPORT_NUMBER("EuPassportNumber"),

    EU_SOCIAL_SECURITY_NUMBER("EuSocialSecurityNumber"),

    EU_TAX_IDENTIFICATION_NUMBER("EuTaxIdentificationNumber"),

    FR_DRIVERS_LICENSE_NUMBER("FrDriversLicenseNumber"),

    FR_HEALTH_INSURANCE_NUMBER("FrHealthInsuranceNumber"),

    FR_NATIONAL_ID("FrNationalId"),

    FR_PASSPORT_NUMBER("FrPassportNumber"),

    FR_SOCIAL_SECURITY_NUMBER("FrSocialSecurityNumber"),

    FR_TAX_IDENTIFICATION_NUMBER("FrTaxIdentificationNumber"),

    FR_VALUE_ADDED_TAX_NUMBER("FrValueAddedTaxNumber"),

    INTERNATIONAL_BANKING_ACCOUNT_NUMBER("InternationalBankingAccountNumber"),

    NZ_BANK_ACCOUNT_NUMBER("NzBankAccountNumber"),

    NZ_DRIVERS_LICENSE_NUMBER("NzDriversLicenseNumber"),

    NZ_INLAND_REVENUE_NUMBER("NzInlandRevenueNumber"),

    NZ_MINISTRY_OF_HEALTH_NUMBER("NzMinistryOfHealthNumber"),

    NZ_SOCIAL_WELFARE_NUMBER("NzSocialWelfareNumber"),

    UK_DRIVERS_LICENSE_NUMBER("UkDriversLicenseNumber"),

    UK_ELECTORAL_ROLL_NUMBER("UkElectoralRollNumber"),

    UK_NATIONAL_HEALTH_NUMBER("UkNationalHealthNumber"),

    UK_NATIONAL_INSURANCE_NUMBER("UkNationalInsuranceNumber"),

    UK_UNIQUE_TAXPAYER_NUMBER("UkUniqueTaxpayerNumber"),

    US_INDIVIDUAL_TAXPAYER_IDENTIFICATION("UsIndividualTaxpayerIdentification");

    private final String value;

    PiiCategory(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
