/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.api.resources.knowledge.types;

import java.util.Optional;

public interface IKnowledgeBaseProperties {
    String getName();

    KnowledgeBaseType getType();

    Optional<String> getUrl();
}
