/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ChartSpecSchema {
    HIGHCHARTS_TS("HIGHCHARTS_TS");

    private final String value;

    ChartSpecSchema(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
