/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mavenagi.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EventConditionGroup.Builder.class)
public final class EventConditionGroup {
    private final PreconditionGroupOperator operator;

    private final List<EventCondition> conditions;

    private final Map<String, Object> additionalProperties;

    private EventConditionGroup(
            PreconditionGroupOperator operator,
            List<EventCondition> conditions,
            Map<String, Object> additionalProperties) {
        this.operator = operator;
        this.conditions = conditions;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return How to combine <code>conditions</code>.
     */
    @JsonProperty("operator")
    public PreconditionGroupOperator getOperator() {
        return operator;
    }

    /**
     * @return The conditions to combine. At least one is required; to match every event, omit the trigger's condition entirely.
     */
    @JsonProperty("conditions")
    public List<EventCondition> getConditions() {
        return conditions;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EventConditionGroup && equalTo((EventConditionGroup) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EventConditionGroup other) {
        return operator.equals(other.operator) && conditions.equals(other.conditions);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.operator, this.conditions);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static OperatorStage builder() {
        return new Builder();
    }

    public interface OperatorStage {
        /**
         * <p>How to combine <code>conditions</code>.</p>
         */
        _FinalStage operator(@NotNull PreconditionGroupOperator operator);

        Builder from(EventConditionGroup other);
    }

    public interface _FinalStage {
        EventConditionGroup build();

        /**
         * <p>The conditions to combine. At least one is required; to match every event, omit the trigger's condition entirely.</p>
         */
        _FinalStage conditions(List<EventCondition> conditions);

        _FinalStage addConditions(EventCondition conditions);

        _FinalStage addAllConditions(List<EventCondition> conditions);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements OperatorStage, _FinalStage {
        private PreconditionGroupOperator operator;

        private List<EventCondition> conditions = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EventConditionGroup other) {
            operator(other.getOperator());
            conditions(other.getConditions());
            return this;
        }

        /**
         * <p>How to combine <code>conditions</code>.</p>
         * <p>How to combine <code>conditions</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("operator")
        public _FinalStage operator(@NotNull PreconditionGroupOperator operator) {
            this.operator = Objects.requireNonNull(operator, "operator must not be null");
            return this;
        }

        /**
         * <p>The conditions to combine. At least one is required; to match every event, omit the trigger's condition entirely.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllConditions(List<EventCondition> conditions) {
            if (conditions != null) {
                this.conditions.addAll(conditions);
            }
            return this;
        }

        /**
         * <p>The conditions to combine. At least one is required; to match every event, omit the trigger's condition entirely.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addConditions(EventCondition conditions) {
            this.conditions.add(conditions);
            return this;
        }

        /**
         * <p>The conditions to combine. At least one is required; to match every event, omit the trigger's condition entirely.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "conditions", nulls = Nulls.SKIP)
        public _FinalStage conditions(List<EventCondition> conditions) {
            this.conditions.clear();
            if (conditions != null) {
                this.conditions.addAll(conditions);
            }
            return this;
        }

        @java.lang.Override
        public EventConditionGroup build() {
            return new EventConditionGroup(operator, conditions, additionalProperties);
        }
    }
}
