/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mavenagi.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = InboxItemBase.Builder.class)
public final class InboxItemBase implements IInboxItemBase {
    private final EntityId id;

    private final OffsetDateTime createdAt;

    private final OffsetDateTime updatedAt;

    private final InboxItemStatus status;

    private final Map<String, Object> additionalProperties;

    private InboxItemBase(
            EntityId id,
            OffsetDateTime createdAt,
            OffsetDateTime updatedAt,
            InboxItemStatus status,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.status = status;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique identifier for the inbox item.
     */
    @JsonProperty("id")
    @java.lang.Override
    public EntityId getId() {
        return id;
    }

    /**
     * @return Timestamp when the inbox item was created.
     */
    @JsonProperty("createdAt")
    @java.lang.Override
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * @return Timestamp when the inbox item was last updated.
     */
    @JsonProperty("updatedAt")
    @java.lang.Override
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * @return Status of the inbox item.
     */
    @JsonProperty("status")
    @java.lang.Override
    public InboxItemStatus getStatus() {
        return status;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof InboxItemBase && equalTo((InboxItemBase) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(InboxItemBase other) {
        return id.equals(other.id)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt)
                && status.equals(other.status);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.createdAt, this.updatedAt, this.status);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>Unique identifier for the inbox item.</p>
         */
        CreatedAtStage id(@NotNull EntityId id);

        Builder from(InboxItemBase other);
    }

    public interface CreatedAtStage {
        /**
         * <p>Timestamp when the inbox item was created.</p>
         */
        UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface UpdatedAtStage {
        /**
         * <p>Timestamp when the inbox item was last updated.</p>
         */
        StatusStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface StatusStage {
        /**
         * <p>Status of the inbox item.</p>
         */
        _FinalStage status(@NotNull InboxItemStatus status);
    }

    public interface _FinalStage {
        InboxItemBase build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, CreatedAtStage, UpdatedAtStage, StatusStage, _FinalStage {
        private EntityId id;

        private OffsetDateTime createdAt;

        private OffsetDateTime updatedAt;

        private InboxItemStatus status;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(InboxItemBase other) {
            id(other.getId());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            status(other.getStatus());
            return this;
        }

        /**
         * <p>Unique identifier for the inbox item.</p>
         * <p>Unique identifier for the inbox item.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public CreatedAtStage id(@NotNull EntityId id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>Timestamp when the inbox item was created.</p>
         * <p>Timestamp when the inbox item was created.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("createdAt")
        public UpdatedAtStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>Timestamp when the inbox item was last updated.</p>
         * <p>Timestamp when the inbox item was last updated.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("updatedAt")
        public StatusStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        /**
         * <p>Status of the inbox item.</p>
         * <p>Status of the inbox item.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public _FinalStage status(@NotNull InboxItemStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        public InboxItemBase build() {
            return new InboxItemBase(id, createdAt, updatedAt, status, additionalProperties);
        }
    }
}
