/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mavenagi.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = KnowledgeBaseInformation.Builder.class)
public final class KnowledgeBaseInformation {
    private final EntityIdWithoutAgent knowledgeBaseId;

    private final Map<String, Object> additionalProperties;

    private KnowledgeBaseInformation(EntityIdWithoutAgent knowledgeBaseId, Map<String, Object> additionalProperties) {
        this.knowledgeBaseId = knowledgeBaseId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique identifier for the knowledge base.
     */
    @JsonProperty("knowledgeBaseId")
    public EntityIdWithoutAgent getKnowledgeBaseId() {
        return knowledgeBaseId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof KnowledgeBaseInformation && equalTo((KnowledgeBaseInformation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(KnowledgeBaseInformation other) {
        return knowledgeBaseId.equals(other.knowledgeBaseId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.knowledgeBaseId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static KnowledgeBaseIdStage builder() {
        return new Builder();
    }

    public interface KnowledgeBaseIdStage {
        /**
         * <p>Unique identifier for the knowledge base.</p>
         */
        _FinalStage knowledgeBaseId(@NotNull EntityIdWithoutAgent knowledgeBaseId);

        Builder from(KnowledgeBaseInformation other);
    }

    public interface _FinalStage {
        KnowledgeBaseInformation build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements KnowledgeBaseIdStage, _FinalStage {
        private EntityIdWithoutAgent knowledgeBaseId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(KnowledgeBaseInformation other) {
            knowledgeBaseId(other.getKnowledgeBaseId());
            return this;
        }

        /**
         * <p>Unique identifier for the knowledge base.</p>
         * <p>Unique identifier for the knowledge base.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("knowledgeBaseId")
        public _FinalStage knowledgeBaseId(@NotNull EntityIdWithoutAgent knowledgeBaseId) {
            this.knowledgeBaseId = Objects.requireNonNull(knowledgeBaseId, "knowledgeBaseId must not be null");
            return this;
        }

        @java.lang.Override
        public KnowledgeBaseInformation build() {
            return new KnowledgeBaseInformation(knowledgeBaseId, additionalProperties);
        }
    }
}
