/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mavenagi.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MetadataEntryCondition.Builder.class)
public final class MetadataEntryCondition {
    private final String key;

    private final MetadataCondition condition;

    private final Map<String, Object> additionalProperties;

    private MetadataEntryCondition(String key, MetadataCondition condition, Map<String, Object> additionalProperties) {
        this.key = key;
        this.condition = condition;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The metadata key to test. A plain key, not a path: metadata is a flat string-to-string map, so there is no nesting to address.
     */
    @JsonProperty("key")
    public String getKey() {
        return key;
    }

    /**
     * @return The condition to evaluate against the value stored under <code>key</code>.
     */
    @JsonProperty("condition")
    public MetadataCondition getCondition() {
        return condition;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MetadataEntryCondition && equalTo((MetadataEntryCondition) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MetadataEntryCondition other) {
        return key.equals(other.key) && condition.equals(other.condition);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.key, this.condition);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static KeyStage builder() {
        return new Builder();
    }

    public interface KeyStage {
        /**
         * <p>The metadata key to test. A plain key, not a path: metadata is a flat string-to-string map, so there is no nesting to address.</p>
         */
        ConditionStage key(@NotNull String key);

        Builder from(MetadataEntryCondition other);
    }

    public interface ConditionStage {
        /**
         * <p>The condition to evaluate against the value stored under <code>key</code>.</p>
         */
        _FinalStage condition(@NotNull MetadataCondition condition);
    }

    public interface _FinalStage {
        MetadataEntryCondition build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements KeyStage, ConditionStage, _FinalStage {
        private String key;

        private MetadataCondition condition;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(MetadataEntryCondition other) {
            key(other.getKey());
            condition(other.getCondition());
            return this;
        }

        /**
         * <p>The metadata key to test. A plain key, not a path: metadata is a flat string-to-string map, so there is no nesting to address.</p>
         * <p>The metadata key to test. A plain key, not a path: metadata is a flat string-to-string map, so there is no nesting to address.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("key")
        public ConditionStage key(@NotNull String key) {
            this.key = Objects.requireNonNull(key, "key must not be null");
            return this;
        }

        /**
         * <p>The condition to evaluate against the value stored under <code>key</code>.</p>
         * <p>The condition to evaluate against the value stored under <code>key</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("condition")
        public _FinalStage condition(@NotNull MetadataCondition condition) {
            this.condition = Objects.requireNonNull(condition, "condition must not be null");
            return this;
        }

        @java.lang.Override
        public MetadataEntryCondition build() {
            return new MetadataEntryCondition(key, condition, additionalProperties);
        }
    }
}
