/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ResolutionStatus {
    public static final ResolutionStatus NEGATIVE_FEEDBACK =
            new ResolutionStatus(Value.NEGATIVE_FEEDBACK, "NEGATIVE_FEEDBACK");

    public static final ResolutionStatus IN_PROGRESS = new ResolutionStatus(Value.IN_PROGRESS, "IN_PROGRESS");

    public static final ResolutionStatus ESCALATED = new ResolutionStatus(Value.ESCALATED, "ESCALATED");

    public static final ResolutionStatus RESOLVED = new ResolutionStatus(Value.RESOLVED, "RESOLVED");

    public static final ResolutionStatus INELIGIBLE = new ResolutionStatus(Value.INELIGIBLE, "INELIGIBLE");

    public static final ResolutionStatus UNKNOWN = new ResolutionStatus(Value.UNKNOWN, "UNKNOWN");

    public static final ResolutionStatus ERROR = new ResolutionStatus(Value.ERROR, "ERROR");

    private final Value value;

    private final String string;

    ResolutionStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ResolutionStatus && this.string.equals(((ResolutionStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case NEGATIVE_FEEDBACK:
                return visitor.visitNegativeFeedback();
            case IN_PROGRESS:
                return visitor.visitInProgress();
            case ESCALATED:
                return visitor.visitEscalated();
            case RESOLVED:
                return visitor.visitResolved();
            case INELIGIBLE:
                return visitor.visitIneligible();
            case UNKNOWN:
                return visitor.visitUnknown();
            case ERROR:
                return visitor.visitError();
            case _UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ResolutionStatus valueOf(String value) {
        switch (value) {
            case "NEGATIVE_FEEDBACK":
                return NEGATIVE_FEEDBACK;
            case "IN_PROGRESS":
                return IN_PROGRESS;
            case "ESCALATED":
                return ESCALATED;
            case "RESOLVED":
                return RESOLVED;
            case "INELIGIBLE":
                return INELIGIBLE;
            case "UNKNOWN":
                return UNKNOWN;
            case "ERROR":
                return ERROR;
            default:
                return new ResolutionStatus(Value._UNKNOWN, value);
        }
    }

    public enum Value {
        UNKNOWN,

        ERROR,

        IN_PROGRESS,

        RESOLVED,

        ESCALATED,

        NEGATIVE_FEEDBACK,

        INELIGIBLE,

        _UNKNOWN
    }

    public interface Visitor<T> {
        T visitUnknown();

        T visitError();

        T visitInProgress();

        T visitResolved();

        T visitEscalated();

        T visitNegativeFeedback();

        T visitIneligible();

        T visitUnknown(String unknownType);
    }
}
