/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mavenagi.core.WrappedAlias;
import java.util.List;

public final class SettingsSchema implements WrappedAlias {
    private final List<SettingsSchemaEntry> value;

    private SettingsSchema(List<SettingsSchemaEntry> value) {
        this.value = value;
    }

    @JsonValue
    public List<SettingsSchemaEntry> get() {
        return this.value;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return this == other || (other instanceof SettingsSchema && this.value.equals(((SettingsSchema) other).value));
    }

    @java.lang.Override
    public int hashCode() {
        return value.hashCode();
    }

    @java.lang.Override
    public String toString() {
        return value.toString();
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SettingsSchema of(List<SettingsSchemaEntry> value) {
        return new SettingsSchema(value);
    }
}
