/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class StringMembershipOperator {
    public static final StringMembershipOperator IN = new StringMembershipOperator(Value.IN, "IN");

    public static final StringMembershipOperator NOT_IN = new StringMembershipOperator(Value.NOT_IN, "NOT_IN");

    private final Value value;

    private final String string;

    StringMembershipOperator(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof StringMembershipOperator
                        && this.string.equals(((StringMembershipOperator) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case IN:
                return visitor.visitIn();
            case NOT_IN:
                return visitor.visitNotIn();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static StringMembershipOperator valueOf(String value) {
        switch (value) {
            case "IN":
                return IN;
            case "NOT_IN":
                return NOT_IN;
            default:
                return new StringMembershipOperator(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        IN,

        NOT_IN,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitIn();

        T visitNotIn();

        T visitUnknown(String unknownType);
    }
}
