/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.commons.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mavenagi.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = StringComparisonCondition.Builder.class)
public final class StringComparisonCondition {
    private final StringComparisonOperator operator;

    private final String value;

    private final Map<String, Object> additionalProperties;

    private StringComparisonCondition(
            StringComparisonOperator operator, String value, Map<String, Object> additionalProperties) {
        this.operator = operator;
        this.value = value;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The comparison operator to apply
     */
    @JsonProperty("operator")
    public StringComparisonOperator getOperator() {
        return operator;
    }

    /**
     * @return The string value to compare against
     */
    @JsonProperty("value")
    public String getValue() {
        return value;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof StringComparisonCondition && equalTo((StringComparisonCondition) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(StringComparisonCondition other) {
        return operator.equals(other.operator) && value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.operator, this.value);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static OperatorStage builder() {
        return new Builder();
    }

    public interface OperatorStage {
        /**
         * <p>The comparison operator to apply</p>
         */
        ValueStage operator(@NotNull StringComparisonOperator operator);

        Builder from(StringComparisonCondition other);
    }

    public interface ValueStage {
        /**
         * <p>The string value to compare against</p>
         */
        _FinalStage value(@NotNull String value);
    }

    public interface _FinalStage {
        StringComparisonCondition build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements OperatorStage, ValueStage, _FinalStage {
        private StringComparisonOperator operator;

        private String value;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(StringComparisonCondition other) {
            operator(other.getOperator());
            value(other.getValue());
            return this;
        }

        /**
         * <p>The comparison operator to apply</p>
         * <p>The comparison operator to apply</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("operator")
        public ValueStage operator(@NotNull StringComparisonOperator operator) {
            this.operator = Objects.requireNonNull(operator, "operator must not be null");
            return this;
        }

        /**
         * <p>The string value to compare against</p>
         * <p>The string value to compare against</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("value")
        public _FinalStage value(@NotNull String value) {
            this.value = Objects.requireNonNull(value, "value must not be null");
            return this;
        }

        @java.lang.Override
        public StringComparisonCondition build() {
            return new StringComparisonCondition(operator, value, additionalProperties);
        }
    }
}
