/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.api.resources.analytics.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

public final class Metric {
    private final Value value;

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    private Metric(Value value) {
        this.value = value;
    }

    public <T> T visit(Visitor<T> visitor) {
        return value.visit(visitor);
    }

    public static Metric count(Count value) {
        return new Metric(new CountValue(value));
    }

    public static Metric sum(Sum value) {
        return new Metric(new SumValue(value));
    }

    public static Metric average(Average value) {
        return new Metric(new AverageValue(value));
    }

    public static Metric min(Min value) {
        return new Metric(new MinValue(value));
    }

    public static Metric max(Max value) {
        return new Metric(new MaxValue(value));
    }

    public static Metric percentile(Percentile value) {
        return new Metric(new PercentileValue(value));
    }

    public static Metric median(Median value) {
        return new Metric(new MedianValue(value));
    }

    public static Metric distinctCount(DistinctCount value) {
        return new Metric(new DistinctCountValue(value));
    }

    public boolean isCount() {
        return value instanceof CountValue;
    }

    public boolean isSum() {
        return value instanceof SumValue;
    }

    public boolean isAverage() {
        return value instanceof AverageValue;
    }

    public boolean isMin() {
        return value instanceof MinValue;
    }

    public boolean isMax() {
        return value instanceof MaxValue;
    }

    public boolean isPercentile() {
        return value instanceof PercentileValue;
    }

    public boolean isMedian() {
        return value instanceof MedianValue;
    }

    public boolean isDistinctCount() {
        return value instanceof DistinctCountValue;
    }

    public boolean _isUnknown() {
        return value instanceof _UnknownValue;
    }

    public Optional<Count> getCount() {
        if (isCount()) {
            return Optional.of(((CountValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Sum> getSum() {
        if (isSum()) {
            return Optional.of(((SumValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Average> getAverage() {
        if (isAverage()) {
            return Optional.of(((AverageValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Min> getMin() {
        if (isMin()) {
            return Optional.of(((MinValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Max> getMax() {
        if (isMax()) {
            return Optional.of(((MaxValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Percentile> getPercentile() {
        if (isPercentile()) {
            return Optional.of(((PercentileValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Median> getMedian() {
        if (isMedian()) {
            return Optional.of(((MedianValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<DistinctCount> getDistinctCount() {
        if (isDistinctCount()) {
            return Optional.of(((DistinctCountValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Object> _getUnknown() {
        if (_isUnknown()) {
            return Optional.of(((_UnknownValue) value).value);
        }
        return Optional.empty();
    }

    @JsonValue
    private Value getValue() {
        return this.value;
    }

    public interface Visitor<T> {
        T visitCount(Count count);

        T visitSum(Sum sum);

        T visitAverage(Average average);

        T visitMin(Min min);

        T visitMax(Max max);

        T visitPercentile(Percentile percentile);

        T visitMedian(Median median);

        T visitDistinctCount(DistinctCount distinctCount);

        T _visitUnknown(Object unknownType);
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = true, defaultImpl = _UnknownValue.class)
    @JsonSubTypes({
        @JsonSubTypes.Type(CountValue.class),
        @JsonSubTypes.Type(SumValue.class),
        @JsonSubTypes.Type(AverageValue.class),
        @JsonSubTypes.Type(MinValue.class),
        @JsonSubTypes.Type(MaxValue.class),
        @JsonSubTypes.Type(PercentileValue.class),
        @JsonSubTypes.Type(MedianValue.class),
        @JsonSubTypes.Type(DistinctCountValue.class)
    })
    @JsonIgnoreProperties(ignoreUnknown = true)
    private interface Value {
        <T> T visit(Visitor<T> visitor);
    }

    @JsonTypeName("count")
    private static final class CountValue implements Value {
        @JsonUnwrapped
        private Count value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private CountValue() {}

        private CountValue(Count value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitCount(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof CountValue && equalTo((CountValue) other);
        }

        private boolean equalTo(CountValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "Metric{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("sum")
    private static final class SumValue implements Value {
        @JsonUnwrapped
        private Sum value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private SumValue() {}

        private SumValue(Sum value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitSum(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof SumValue && equalTo((SumValue) other);
        }

        private boolean equalTo(SumValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "Metric{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("average")
    private static final class AverageValue implements Value {
        @JsonUnwrapped
        private Average value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private AverageValue() {}

        private AverageValue(Average value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitAverage(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof AverageValue && equalTo((AverageValue) other);
        }

        private boolean equalTo(AverageValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "Metric{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("min")
    private static final class MinValue implements Value {
        @JsonUnwrapped
        private Min value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private MinValue() {}

        private MinValue(Min value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitMin(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof MinValue && equalTo((MinValue) other);
        }

        private boolean equalTo(MinValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "Metric{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("max")
    private static final class MaxValue implements Value {
        @JsonUnwrapped
        private Max value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private MaxValue() {}

        private MaxValue(Max value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitMax(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof MaxValue && equalTo((MaxValue) other);
        }

        private boolean equalTo(MaxValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "Metric{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("percentile")
    private static final class PercentileValue implements Value {
        @JsonUnwrapped
        private Percentile value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private PercentileValue() {}

        private PercentileValue(Percentile value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitPercentile(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof PercentileValue && equalTo((PercentileValue) other);
        }

        private boolean equalTo(PercentileValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "Metric{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("median")
    private static final class MedianValue implements Value {
        @JsonUnwrapped
        private Median value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private MedianValue() {}

        private MedianValue(Median value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitMedian(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof MedianValue && equalTo((MedianValue) other);
        }

        private boolean equalTo(MedianValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "Metric{" + "value: " + value + "}";
        }
    }

    @JsonTypeName("distinctCount")
    private static final class DistinctCountValue implements Value {
        @JsonUnwrapped
        private DistinctCount value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private DistinctCountValue() {}

        private DistinctCountValue(DistinctCount value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitDistinctCount(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof DistinctCountValue && equalTo((DistinctCountValue) other);
        }

        private boolean equalTo(DistinctCountValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "Metric{" + "value: " + value + "}";
        }
    }

    private static final class _UnknownValue implements Value {
        private String type;

        @JsonValue
        private Object value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private _UnknownValue(@JsonProperty("value") Object value) {}

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor._visitUnknown(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof _UnknownValue && equalTo((_UnknownValue) other);
        }

        private boolean equalTo(_UnknownValue other) {
            return type.equals(other.type) && value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.type, this.value);
        }

        @java.lang.Override
        public String toString() {
            return "Metric{" + "type: " + type + ", value: " + value + "}";
        }
    }
}
