/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.conversation.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.mavenagi.core.ObjectMappers;
import java.io.IOException;
import java.util.Objects;

@JsonDeserialize(using = ActionFormRequestParamValue.Deserializer.class)
public final class ActionFormRequestParamValue {
    private final Object value;

    private final int type;

    private ActionFormRequestParamValue(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((Object) this.value);
        } else if (this.type == 1) {
            return visitor.visit((ActionFormAttachment) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ActionFormRequestParamValue && equalTo((ActionFormRequestParamValue) other);
    }

    private boolean equalTo(ActionFormRequestParamValue other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static ActionFormRequestParamValue of(Object value) {
        return new ActionFormRequestParamValue(value, 0);
    }

    public static ActionFormRequestParamValue of(ActionFormAttachment value) {
        return new ActionFormRequestParamValue(value, 1);
    }

    public interface Visitor<T> {
        T visit(Object value);

        T visit(ActionFormAttachment value);
    }

    static final class Deserializer extends StdDeserializer<ActionFormRequestParamValue> {
        Deserializer() {
            super(ActionFormRequestParamValue.class);
        }

        @java.lang.Override
        public ActionFormRequestParamValue deserialize(JsonParser p, DeserializationContext context)
                throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, Object.class));
            } catch (IllegalArgumentException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, ActionFormAttachment.class));
            } catch (IllegalArgumentException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
