/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.commons.errors;

import com.mavenagi.core.MavenAGIApiException;
import com.mavenagi.resources.commons.types.ErrorMessage;
import okhttp3.Response;

public final class ServerError extends MavenAGIApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final ErrorMessage body;

    public ServerError(ErrorMessage body) {
        super("ServerError", 500, body);
        this.body = body;
    }

    public ServerError(ErrorMessage body, Response rawResponse) {
        super("ServerError", 500, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public ErrorMessage body() {
        return this.body;
    }
}
