/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.intelligentfields.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mavenagi.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EnumOption.Builder.class)
public final class EnumOption {
    private final String value;

    private final Optional<String> label;

    private final Optional<String> description;

    private final Map<String, Object> additionalProperties;

    private EnumOption(
            String value,
            Optional<String> label,
            Optional<String> description,
            Map<String, Object> additionalProperties) {
        this.value = value;
        this.label = label;
        this.description = description;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The value of the option
     */
    @JsonProperty("value")
    public String getValue() {
        return value;
    }

    /**
     * @return Display label for the option
     */
    @JsonProperty("label")
    public Optional<String> getLabel() {
        return label;
    }

    /**
     * @return Instructions that tell the LLM when to pick this option. Up to 1200 characters. On a
     * patch, an option sent without a description has its description cleared.
     */
    @JsonProperty("description")
    public Optional<String> getDescription() {
        return description;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EnumOption && equalTo((EnumOption) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EnumOption other) {
        return value.equals(other.value) && label.equals(other.label) && description.equals(other.description);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value, this.label, this.description);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ValueStage builder() {
        return new Builder();
    }

    public interface ValueStage {
        /**
         * <p>The value of the option</p>
         */
        _FinalStage value(@NotNull String value);

        Builder from(EnumOption other);
    }

    public interface _FinalStage {
        EnumOption build();

        /**
         * <p>Display label for the option</p>
         */
        _FinalStage label(Optional<String> label);

        _FinalStage label(String label);

        /**
         * <p>Instructions that tell the LLM when to pick this option. Up to 1200 characters. On a
         * patch, an option sent without a description has its description cleared.</p>
         */
        _FinalStage description(Optional<String> description);

        _FinalStage description(String description);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ValueStage, _FinalStage {
        private String value;

        private Optional<String> description = Optional.empty();

        private Optional<String> label = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EnumOption other) {
            value(other.getValue());
            label(other.getLabel());
            description(other.getDescription());
            return this;
        }

        /**
         * <p>The value of the option</p>
         * <p>The value of the option</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("value")
        public _FinalStage value(@NotNull String value) {
            this.value = Objects.requireNonNull(value, "value must not be null");
            return this;
        }

        /**
         * <p>Instructions that tell the LLM when to pick this option. Up to 1200 characters. On a
         * patch, an option sent without a description has its description cleared.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * <p>Instructions that tell the LLM when to pick this option. Up to 1200 characters. On a
         * patch, an option sent without a description has its description cleared.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public _FinalStage description(Optional<String> description) {
            this.description = description;
            return this;
        }

        /**
         * <p>Display label for the option</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage label(String label) {
            this.label = Optional.ofNullable(label);
            return this;
        }

        /**
         * <p>Display label for the option</p>
         */
        @java.lang.Override
        @JsonSetter(value = "label", nulls = Nulls.SKIP)
        public _FinalStage label(Optional<String> label) {
            this.label = label;
            return this;
        }

        @java.lang.Override
        public EnumOption build() {
            return new EnumOption(value, label, description, additionalProperties);
        }
    }
}
