/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.intelligentfields.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mavenagi.core.ObjectMappers;
import com.mavenagi.resources.commons.types.EntityId;
import com.mavenagi.resources.commons.types.EntityIdWithoutAgent;
import com.mavenagi.resources.commons.types.EntityType;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IntelligentFieldResponse.Builder.class)
public final class IntelligentFieldResponse
        implements IIntelligentFieldResponse, IIntelligentFieldBase, IIntelligentFieldCore {
    private final EntityId fieldId;

    private final IntelligentFieldStatus status;

    private final Optional<OffsetDateTime> createdAt;

    private final Optional<OffsetDateTime> updatedAt;

    private final EntityType entityType;

    private final Optional<EntityIdWithoutAgent> variantId;

    private final String name;

    private final Optional<String> description;

    private final IntelligentFieldType validationType;

    private final String definition;

    private final Optional<List<EnumOption>> enumOptions;

    private final Map<String, Object> additionalProperties;

    private IntelligentFieldResponse(
            EntityId fieldId,
            IntelligentFieldStatus status,
            Optional<OffsetDateTime> createdAt,
            Optional<OffsetDateTime> updatedAt,
            EntityType entityType,
            Optional<EntityIdWithoutAgent> variantId,
            String name,
            Optional<String> description,
            IntelligentFieldType validationType,
            String definition,
            Optional<List<EnumOption>> enumOptions,
            Map<String, Object> additionalProperties) {
        this.fieldId = fieldId;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.entityType = entityType;
        this.variantId = variantId;
        this.name = name;
        this.description = description;
        this.validationType = validationType;
        this.definition = definition;
        this.enumOptions = enumOptions;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return ID that uniquely identifies this intelligent field
     */
    @JsonProperty("fieldId")
    @java.lang.Override
    public EntityId getFieldId() {
        return fieldId;
    }

    /**
     * @return Lifecycle state for whether this field is evaluated by workflows. Defaults to INACTIVE on creation. Use PATCH to activate.
     */
    @JsonProperty("status")
    @java.lang.Override
    public IntelligentFieldStatus getStatus() {
        return status;
    }

    /**
     * @return The date and time the intelligent field was created
     */
    @JsonProperty("createdAt")
    @java.lang.Override
    public Optional<OffsetDateTime> getCreatedAt() {
        return createdAt;
    }

    /**
     * @return The date and time the intelligent field was last updated
     */
    @JsonProperty("updatedAt")
    @java.lang.Override
    public Optional<OffsetDateTime> getUpdatedAt() {
        return updatedAt;
    }

    /**
     * @return Target entity type for evaluation. Only CONVERSATION is supported at this time. The backend will return an error for other types.
     */
    @JsonProperty("entityType")
    @java.lang.Override
    public EntityType getEntityType() {
        return entityType;
    }

    /**
     * @return ID of the agent variant that created this field, if applicable
     */
    @JsonProperty("variantId")
    @java.lang.Override
    public Optional<EntityIdWithoutAgent> getVariantId() {
        return variantId;
    }

    /**
     * @return Display name for the intelligent field
     */
    @JsonProperty("name")
    @java.lang.Override
    public String getName() {
        return name;
    }

    /**
     * @return A plain text description of the intelligent field.
     */
    @JsonProperty("description")
    @java.lang.Override
    public Optional<String> getDescription() {
        return description;
    }

    /**
     * @return Result type hint used for schema generation, UI, and validation.
     * <ul>
     * <li>STRING / MULTILINE: single string value</li>
     * <li>MULTI_SELECT: multiple values</li>
     * <li>BOOLEAN: boolean value</li>
     * <li>NUMBER: numeric value</li>
     * </ul>
     * <p>Note: for single select, use STRING/NUMBER with a list of enumOptions.</p>
     */
    @JsonProperty("validationType")
    @java.lang.Override
    public IntelligentFieldType getValidationType() {
        return validationType;
    }

    /**
     * @return Definition used by the LLM when generating this field's value
     */
    @JsonProperty("definition")
    @java.lang.Override
    public String getDefinition() {
        return definition;
    }

    /**
     * @return Optional enum options for STRING/MULTILINE/NUMBER when a finite set is desired
     */
    @JsonProperty("enumOptions")
    @java.lang.Override
    public Optional<List<EnumOption>> getEnumOptions() {
        return enumOptions;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IntelligentFieldResponse && equalTo((IntelligentFieldResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IntelligentFieldResponse other) {
        return fieldId.equals(other.fieldId)
                && status.equals(other.status)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt)
                && entityType.equals(other.entityType)
                && variantId.equals(other.variantId)
                && name.equals(other.name)
                && description.equals(other.description)
                && validationType.equals(other.validationType)
                && definition.equals(other.definition)
                && enumOptions.equals(other.enumOptions);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.fieldId,
                this.status,
                this.createdAt,
                this.updatedAt,
                this.entityType,
                this.variantId,
                this.name,
                this.description,
                this.validationType,
                this.definition,
                this.enumOptions);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FieldIdStage builder() {
        return new Builder();
    }

    public interface FieldIdStage {
        /**
         * <p>ID that uniquely identifies this intelligent field</p>
         */
        StatusStage fieldId(@NotNull EntityId fieldId);

        Builder from(IntelligentFieldResponse other);
    }

    public interface StatusStage {
        /**
         * <p>Lifecycle state for whether this field is evaluated by workflows. Defaults to INACTIVE on creation. Use PATCH to activate.</p>
         */
        EntityTypeStage status(@NotNull IntelligentFieldStatus status);
    }

    public interface EntityTypeStage {
        /**
         * <p>Target entity type for evaluation. Only CONVERSATION is supported at this time. The backend will return an error for other types.</p>
         */
        NameStage entityType(@NotNull EntityType entityType);
    }

    public interface NameStage {
        /**
         * <p>Display name for the intelligent field</p>
         */
        ValidationTypeStage name(@NotNull String name);
    }

    public interface ValidationTypeStage {
        /**
         * <p>Result type hint used for schema generation, UI, and validation.</p>
         * <ul>
         * <li>STRING / MULTILINE: single string value</li>
         * <li>MULTI_SELECT: multiple values</li>
         * <li>BOOLEAN: boolean value</li>
         * <li>NUMBER: numeric value</li>
         * </ul>
         * <p>Note: for single select, use STRING/NUMBER with a list of enumOptions.</p>
         */
        DefinitionStage validationType(@NotNull IntelligentFieldType validationType);
    }

    public interface DefinitionStage {
        /**
         * <p>Definition used by the LLM when generating this field's value</p>
         */
        _FinalStage definition(@NotNull String definition);
    }

    public interface _FinalStage {
        IntelligentFieldResponse build();

        /**
         * <p>The date and time the intelligent field was created</p>
         */
        _FinalStage createdAt(Optional<OffsetDateTime> createdAt);

        _FinalStage createdAt(OffsetDateTime createdAt);

        /**
         * <p>The date and time the intelligent field was last updated</p>
         */
        _FinalStage updatedAt(Optional<OffsetDateTime> updatedAt);

        _FinalStage updatedAt(OffsetDateTime updatedAt);

        /**
         * <p>ID of the agent variant that created this field, if applicable</p>
         */
        _FinalStage variantId(Optional<EntityIdWithoutAgent> variantId);

        _FinalStage variantId(EntityIdWithoutAgent variantId);

        /**
         * <p>A plain text description of the intelligent field.</p>
         */
        _FinalStage description(Optional<String> description);

        _FinalStage description(String description);

        /**
         * <p>Optional enum options for STRING/MULTILINE/NUMBER when a finite set is desired</p>
         */
        _FinalStage enumOptions(Optional<List<EnumOption>> enumOptions);

        _FinalStage enumOptions(List<EnumOption> enumOptions);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements FieldIdStage,
                    StatusStage,
                    EntityTypeStage,
                    NameStage,
                    ValidationTypeStage,
                    DefinitionStage,
                    _FinalStage {
        private EntityId fieldId;

        private IntelligentFieldStatus status;

        private EntityType entityType;

        private String name;

        private IntelligentFieldType validationType;

        private String definition;

        private Optional<List<EnumOption>> enumOptions = Optional.empty();

        private Optional<String> description = Optional.empty();

        private Optional<EntityIdWithoutAgent> variantId = Optional.empty();

        private Optional<OffsetDateTime> updatedAt = Optional.empty();

        private Optional<OffsetDateTime> createdAt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(IntelligentFieldResponse other) {
            fieldId(other.getFieldId());
            status(other.getStatus());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            entityType(other.getEntityType());
            variantId(other.getVariantId());
            name(other.getName());
            description(other.getDescription());
            validationType(other.getValidationType());
            definition(other.getDefinition());
            enumOptions(other.getEnumOptions());
            return this;
        }

        /**
         * <p>ID that uniquely identifies this intelligent field</p>
         * <p>ID that uniquely identifies this intelligent field</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("fieldId")
        public StatusStage fieldId(@NotNull EntityId fieldId) {
            this.fieldId = Objects.requireNonNull(fieldId, "fieldId must not be null");
            return this;
        }

        /**
         * <p>Lifecycle state for whether this field is evaluated by workflows. Defaults to INACTIVE on creation. Use PATCH to activate.</p>
         * <p>Lifecycle state for whether this field is evaluated by workflows. Defaults to INACTIVE on creation. Use PATCH to activate.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public EntityTypeStage status(@NotNull IntelligentFieldStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        /**
         * <p>Target entity type for evaluation. Only CONVERSATION is supported at this time. The backend will return an error for other types.</p>
         * <p>Target entity type for evaluation. Only CONVERSATION is supported at this time. The backend will return an error for other types.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("entityType")
        public NameStage entityType(@NotNull EntityType entityType) {
            this.entityType = Objects.requireNonNull(entityType, "entityType must not be null");
            return this;
        }

        /**
         * <p>Display name for the intelligent field</p>
         * <p>Display name for the intelligent field</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public ValidationTypeStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Result type hint used for schema generation, UI, and validation.</p>
         * <ul>
         * <li>STRING / MULTILINE: single string value</li>
         * <li>MULTI_SELECT: multiple values</li>
         * <li>BOOLEAN: boolean value</li>
         * <li>NUMBER: numeric value</li>
         * </ul>
         * <p>Note: for single select, use STRING/NUMBER with a list of enumOptions.</p>
         * <p>Result type hint used for schema generation, UI, and validation.</p>
         * <ul>
         * <li>STRING / MULTILINE: single string value</li>
         * <li>MULTI_SELECT: multiple values</li>
         * <li>BOOLEAN: boolean value</li>
         * <li>NUMBER: numeric value</li>
         * </ul>
         * <p>Note: for single select, use STRING/NUMBER with a list of enumOptions.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("validationType")
        public DefinitionStage validationType(@NotNull IntelligentFieldType validationType) {
            this.validationType = Objects.requireNonNull(validationType, "validationType must not be null");
            return this;
        }

        /**
         * <p>Definition used by the LLM when generating this field's value</p>
         * <p>Definition used by the LLM when generating this field's value</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("definition")
        public _FinalStage definition(@NotNull String definition) {
            this.definition = Objects.requireNonNull(definition, "definition must not be null");
            return this;
        }

        /**
         * <p>Optional enum options for STRING/MULTILINE/NUMBER when a finite set is desired</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage enumOptions(List<EnumOption> enumOptions) {
            this.enumOptions = Optional.ofNullable(enumOptions);
            return this;
        }

        /**
         * <p>Optional enum options for STRING/MULTILINE/NUMBER when a finite set is desired</p>
         */
        @java.lang.Override
        @JsonSetter(value = "enumOptions", nulls = Nulls.SKIP)
        public _FinalStage enumOptions(Optional<List<EnumOption>> enumOptions) {
            this.enumOptions = enumOptions;
            return this;
        }

        /**
         * <p>A plain text description of the intelligent field.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * <p>A plain text description of the intelligent field.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public _FinalStage description(Optional<String> description) {
            this.description = description;
            return this;
        }

        /**
         * <p>ID of the agent variant that created this field, if applicable</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage variantId(EntityIdWithoutAgent variantId) {
            this.variantId = Optional.ofNullable(variantId);
            return this;
        }

        /**
         * <p>ID of the agent variant that created this field, if applicable</p>
         */
        @java.lang.Override
        @JsonSetter(value = "variantId", nulls = Nulls.SKIP)
        public _FinalStage variantId(Optional<EntityIdWithoutAgent> variantId) {
            this.variantId = variantId;
            return this;
        }

        /**
         * <p>The date and time the intelligent field was last updated</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage updatedAt(OffsetDateTime updatedAt) {
            this.updatedAt = Optional.ofNullable(updatedAt);
            return this;
        }

        /**
         * <p>The date and time the intelligent field was last updated</p>
         */
        @java.lang.Override
        @JsonSetter(value = "updatedAt", nulls = Nulls.SKIP)
        public _FinalStage updatedAt(Optional<OffsetDateTime> updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * <p>The date and time the intelligent field was created</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage createdAt(OffsetDateTime createdAt) {
            this.createdAt = Optional.ofNullable(createdAt);
            return this;
        }

        /**
         * <p>The date and time the intelligent field was created</p>
         */
        @java.lang.Override
        @JsonSetter(value = "createdAt", nulls = Nulls.SKIP)
        public _FinalStage createdAt(Optional<OffsetDateTime> createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.Override
        public IntelligentFieldResponse build() {
            return new IntelligentFieldResponse(
                    fieldId,
                    status,
                    createdAt,
                    updatedAt,
                    entityType,
                    variantId,
                    name,
                    description,
                    validationType,
                    definition,
                    enumOptions,
                    additionalProperties);
        }
    }
}
