/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.intelligentfields.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class IntelligentFieldStatus {
    public static final IntelligentFieldStatus DELETED = new IntelligentFieldStatus(Value.DELETED, "DELETED");

    public static final IntelligentFieldStatus ACTIVE = new IntelligentFieldStatus(Value.ACTIVE, "ACTIVE");

    public static final IntelligentFieldStatus INACTIVE = new IntelligentFieldStatus(Value.INACTIVE, "INACTIVE");

    private final Value value;

    private final String string;

    IntelligentFieldStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof IntelligentFieldStatus
                        && this.string.equals(((IntelligentFieldStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DELETED:
                return visitor.visitDeleted();
            case ACTIVE:
                return visitor.visitActive();
            case INACTIVE:
                return visitor.visitInactive();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static IntelligentFieldStatus valueOf(String value) {
        switch (value) {
            case "DELETED":
                return DELETED;
            case "ACTIVE":
                return ACTIVE;
            case "INACTIVE":
                return INACTIVE;
            default:
                return new IntelligentFieldStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ACTIVE,

        INACTIVE,

        DELETED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitActive();

        T visitInactive();

        T visitDeleted();

        T visitUnknown(String unknownType);
    }
}
