/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.mavenagi.resources.intelligentfields.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mavenagi.core.ObjectMappers;
import com.mavenagi.resources.commons.types.EntityId;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IntelligentFieldValueFieldFilter.Builder.class)
public final class IntelligentFieldValueFieldFilter {
    private final Optional<List<EntityId>> fieldIds;

    private final Optional<List<IntelligentFieldType>> validationTypes;

    private final Map<String, Object> additionalProperties;

    private IntelligentFieldValueFieldFilter(
            Optional<List<EntityId>> fieldIds,
            Optional<List<IntelligentFieldType>> validationTypes,
            Map<String, Object> additionalProperties) {
        this.fieldIds = fieldIds;
        this.validationTypes = validationTypes;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Filter to specific fields by their entity IDs. OR semantics. Maximum 100 IDs.
     */
    @JsonProperty("fieldIds")
    public Optional<List<EntityId>> getFieldIds() {
        return fieldIds;
    }

    /**
     * @return Filter by field validation type (STRING, MULTILINE, MULTI_SELECT, BOOLEAN, NUMBER). OR semantics.
     */
    @JsonProperty("validationTypes")
    public Optional<List<IntelligentFieldType>> getValidationTypes() {
        return validationTypes;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IntelligentFieldValueFieldFilter && equalTo((IntelligentFieldValueFieldFilter) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IntelligentFieldValueFieldFilter other) {
        return fieldIds.equals(other.fieldIds) && validationTypes.equals(other.validationTypes);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.fieldIds, this.validationTypes);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<EntityId>> fieldIds = Optional.empty();

        private Optional<List<IntelligentFieldType>> validationTypes = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(IntelligentFieldValueFieldFilter other) {
            fieldIds(other.getFieldIds());
            validationTypes(other.getValidationTypes());
            return this;
        }

        /**
         * <p>Filter to specific fields by their entity IDs. OR semantics. Maximum 100 IDs.</p>
         */
        @JsonSetter(value = "fieldIds", nulls = Nulls.SKIP)
        public Builder fieldIds(Optional<List<EntityId>> fieldIds) {
            this.fieldIds = fieldIds;
            return this;
        }

        public Builder fieldIds(List<EntityId> fieldIds) {
            this.fieldIds = Optional.ofNullable(fieldIds);
            return this;
        }

        /**
         * <p>Filter by field validation type (STRING, MULTILINE, MULTI_SELECT, BOOLEAN, NUMBER). OR semantics.</p>
         */
        @JsonSetter(value = "validationTypes", nulls = Nulls.SKIP)
        public Builder validationTypes(Optional<List<IntelligentFieldType>> validationTypes) {
            this.validationTypes = validationTypes;
            return this;
        }

        public Builder validationTypes(List<IntelligentFieldType> validationTypes) {
            this.validationTypes = Optional.ofNullable(validationTypes);
            return this;
        }

        public IntelligentFieldValueFieldFilter build() {
            return new IntelligentFieldValueFieldFilter(fieldIds, validationTypes, additionalProperties);
        }
    }
}
